### ISSUE TITLE
运行报错了，关于Androidx

### ISSUE THREAD

**Issue by manburenshenglu** [CarGuo/gsy_github_app_flutter#567]
![image](https://user-images.githubusercontent.com/13146756/66699792-47253a00-ed1c-11e9-9185-424ba43bfa83.png)

**Comment by CarGuo** [comment]
你本地的flutter版本是？

**Comment by CarGuo** [comment]
我这边测试正常，目前 1.9.1 hotfix4

**Comment by manburenshenglu** [comment]
![image](https://user-images.githubusercontent.com/13146756/66700366-05978d80-ed22-11e9-9b02-d2dc8fed7456.png)
这是我的flutter版本

**Comment by CarGuo** [comment]
请切换到 stable 分支，用稳定版版本。

**Comment by manburenshenglu** [comment]
好的，我试试看

**Comment by manburenshenglu** [comment]
好了，我切换到stable channel并执行了flutter upgrade升级到 1.9.1 hotfix4，跑起来了，谢谢
