### ISSUE TITLE
一个小bug，搜索页排序，排序，写错了

### ISSUE THREAD

**Issue by chenshipeng** [CarGuo/gsy_github_app_flutter#568]
![WechatIMG7](https://user-images.githubusercontent.com/2504666/66738108-4f0de700-eea0-11e9-8b16-845775dcd24c.jpeg)
![WechatIMG8](https://user-images.githubusercontent.com/2504666/66738249-94caaf80-eea0-11e9-8dd1-f45623f2ca40.jpeg)

**Comment by CarGuo** [comment]
收到，thx
