### ISSUE TITLE
仿写项目 

### ISSUE THREAD

**Issue by iOSyifeng** [CarGuo/gsy_github_app_flutter#570]
最近已经读了好几篇 关于 Flutter 的文章 作者的Flutter 系列 也已经读完了 现在想仿写一个Flutter 项目  作者有啥好的推荐么 不希望太难, 作者的 github_app 适合新手仿写么

**Comment by CarGuo** [comment]
我个人觉得还行，推荐还有 wanAndroid 客户端，ganki o客户端等也有开源参考
