### ISSUE TITLE
退出账号后无法再次登录，报 422错误

### ISSUE THREAD

**Issue by shenbh** [CarGuo/gsy_github_app_flutter#573]
退出账号后无法再次登录，报 422错误

**Comment by shenbh** [comment]
I/flutter ( 9699): 请求参数: {"scopes":["user","repo","gist","notifications"],"note":"admin_script"}
I/flutter ( 9699): 请求异常: DioError [DioErrorType.RESPONSE]: Http status error [422]
I/flutter ( 9699): 请求异常信息: {"message":"Validation Failed","errors":[{"resource":"OauthAccess","code":"already_exists","field":"note"}],

**Comment by CarGuo** [comment]
我这边测试正常，退出账号后应该已经清楚了 token 啊

**Comment by CarGuo** [comment]
测试正常，自己编译的请确保 client_id  client_secret 是正确的，申请方法看readme
