### ISSUE TITLE
退出账户后，无法再次登录包422，"code":"already_exists"

### ISSUE THREAD

**Issue by iloveclanguage** [CarGuo/gsy_github_app_flutter#574]
I/flutter ( 3280): 请求url：https://api.github.com/authorizations
I/flutter ( 3280): 请求头: {content-type: application/json; charset=utf-8, Authorization: Basic aWxvdmVjbGFuZ3VhZ2U6MTk4MzEwMTNEdWFuenk=}
I/flutter ( 3280): 请求参数: {"scopes":["user","repo","gist","notifications"],"note":"admin_script","client_id":"ilovec","client_secret":""}
I/flutter ( 3280): 请求异常: DioError [DioErrorType.RESPONSE]: Http status error [422]
I/flutter ( 3280): 请求异常信息: {"message":"Validation Failed","errors":[{"resource":"OauthAccess","code":"already_exists","field":"note"}],"documentation_url":"https://developer.github.com/v3/oauth_authorizations/#create-a-new-authorization"}
D/EGL_emulation( 3280): eglMakeCurrent: 0x7639a6bd6d60: ver 2 0 (tinfo 0x7639973f3440)
D/EGL_emulation( 3280): eglMakeCurrent: 0x7639a6bd6d60: ver 2 0 (tinfo 0x7639973f3440)

**Comment by CarGuo** [comment]
测试正常，请确定你的 client_id 和 client_secret 是正确的
