### ISSUE TITLE
华为p9测试，输入密码时会遮挡UI控件。

### ISSUE THREAD

**Issue by Aaron009** [CarGuo/gsy_github_app_flutter#580]
@CarGuo @YinRenjie1993 @xzchsia @CarGuoSmall

我查了一下，这个问题好像以前修复过。我特定通过source tree检查了一下，确定拉的是最新版本。
我自己也写一个APP，但是也没遇到键盘遮挡控件的问题。
本来想自己修复的，无奈没有查出问题。

问题截图如下
![微信图片_20191122173010](https://user-images.githubusercontent.com/3838050/69414595-032b4900-0d4e-11ea-987a-b80013d9e047.jpg)

**Comment by Aaron009** [comment]
我把Flutter SDK版本降级为Stable版本就好了。
我也是今天才知道，flutter版本管理很简单，直接通过git切换分支就好了。

版本如下。
```shell
Flutter 1.9.1+hotfix.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 68587a0916 (10 weeks ago) • 2019-09-13 19:46:58 -0700
Engine • revision b863200c37
Tools • Dart 2.5.0
```

**Comment by CarGuo** [comment]
是的····

**Comment by lawlietwind** [comment]
把所有关于`NavigatorUtils.pageContainer()`地方去掉就没问题了，相关代码如下：
```Dart
  ///Page页面的容器，做一次通用自定义
  static Widget pageContainer(widget) {
    return MediaQuery(

        ///不受系统字体缩放影响
        data: MediaQueryData.fromWindow(WidgetsBinding.instance.window)
            .copyWith(textScaleFactor: 1),
        child: widget);
  }
```
具体原因尚未发现，不过可以确定flutter新版本(1.12以后)会出现这个bug。

**Comment by CarGuo** [comment]
@lawlietwind  你是用 1.12 测试后的时候，用的是 dev_next 分支吗？

**Comment by lawlietwind** [comment]
不是，是之前的版本，master分支上，最近打开出现了这个问题，最新版本没有进行测试
