### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by perplexedfeathers** [CarGuo/gsy_github_app_flutter#581]
Unsupported operation: Cannot extract a file path from a URI with a query component
 #0      _SimpleUri.toFilePath (dart:core/uri.dart:4709)
#1      new File.fromUri (dart:io/file.dart:265)
#2      MarkdownBuilder._buildImage (package:flutter_markdown/src/builder.dart:358)
#3      MarkdownBuilder.visitElementAfter (package:flutter_markdown/src/builder.dart:288)
#4      Element.accept (package:markdown/src/ast.dart:51)
#5      Element.accept (package:markdown/src/ast.dart:48)
#6      Element.accept (package:markdown/src/ast.dart:48)
#7      MarkdownBuilder.build (package:flutter_markdown/src/builder.dart:139)
#8      _MarkdownWidgetState._parseMarkdown (package:flutter_markdown/src/widget.dart:144)
#9      _MarkdownWidgetState.didChangeDependencies (package:flutter_markdown/src/widget.dart:110)
#10     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4086)
#11     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919)
#12     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101)
#13     Element.updateChild (package:flutter/src/widgets/framework.dart:2904)
#14     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127)
#15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101)
#16     Element.updateChild (package:flutter/src/widgets/framework.dart:2904)
#17     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127)
#18     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101)
#19     Element.updateChild (package:flutter/src/widgets/framework.dart:2904)
#20     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127)
#21     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101)
#22     Element.updateChild (package:flutter/src/widgets/framework.dart:2904)
#23     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127)
#24     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101)
#25     Element.updateChild (package:flutter/src/widgets/framework.dart:2904)
#26     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961)
#27     Element.rebuild (package:flutter/src/widgets/framework.dart:3738)
#28     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924)
#29     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919)
#30     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101)
#31     Element.updateChild (package:flutter/src/widgets/framework.dart:2904)
#32     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127)
#33     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101)
#34     Element.updateChild (package:flutter/src/widgets/framework.dart:2904)
#35     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961)
#36     Element.rebuild (package:flutter/src/widgets/framework.dart:3738)
#37     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924)
#38     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4088)
#39     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919)
#40     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101)
#41     Element.updateChild (package:flutter/src/widgets/framework.dart:2904)
#42     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127)
#43     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101)
#44     Element.updateChild (package:flutter/src/widgets/framework.dart:2904)
#45     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961)
#46     Element.rebuild (package:flutter/src/widgets/framework.dart:3738)
#47     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924)
#48     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919)
#49     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101)
#50     Element.updateChild (package:flutter/src/widgets/framework.dart:2904)
#51     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961)
#52     Element.rebuild (package:flutter/src/widgets/framework.dart:3738)
#53     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924)
#54     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919)
#55     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101)
#56     Element.updateChild (package:flutter/src/widgets/framework.dart:2904)
#57     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127)
#58     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101)
#59     Element.updateChild (package:flutter/src/widgets/framework.dart:2904)
#60     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127)
#61     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101)
#62     Element.updateChild (package:flutter/src/widgets/framework.dart:2904)
#63     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127)
#64     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101)
#65     Element.updateChild (package:flutter/src/widgets/framework.dart:2904)
#66     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127)
#67     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101)
#68     Element.updateChild (package:flutter/src/widgets/framework.dart:2904)
#69     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961)
#70     Element.rebuild (package:flutter/src/widgets/framework.dart:3738)
#71     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924)
#72     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919)
#73     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101)
#74     Element.updateChild (package:flutter/src/widgets/framework.dart:2904)
#75     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961)
#76     Element.rebuild (package:flutter/src/widgets/framework.dart:3738)
#77     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924)
#78     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4088)
#79     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919)
#80     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101)
#81     Element.updateChild (package:flutter/src/widgets/framework.dart:2904)
#82     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961)
#83     Element.rebuild (package:flutter/src/widgets/framework.dart:3738)
#84     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924)
#85     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4088)
#86     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919)
#87     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101)
#88     Element.updateChild (package:flutter/src/widgets/framework.dart:2904)
#89     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961)
#90     Element.rebuild (package:flutter/src/widgets/framework.dart:3738)
#91     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924)
#92     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919)
#93     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101)
#94     Element.updateChild (package:flutter/src/widgets/framework.dart:2904)
#95     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961)
#96     Element.rebuild (package:flutter/src/widgets/framework.dart:3738)
#97     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924)
#98     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919)
#99     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101)
#100    Element.updateChild (package:flutter/src/widgets/framework.dart:2904)
#101    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127)
#102    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101)
#103    Element.updateChild (package:flutter/src/widgets/framework.dart:2904)
#104    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127)
#105    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101)
#106    Element.updateChild (package:flutter/src/widgets/framework.dart:2904)
#107    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961)
#108    Element.rebuild (package:flutter/src/widgets/framework.dart:3738)
#109    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924)
#110    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919)
#111    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101)
#112    Element.updateChild (package:flutter/src/widgets/framework.dart:2904)
#113    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961)
#114    Element.rebuild (package:flutter/src/widgets/framework.dart:3738)
#115    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924)
#116    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919)
#117    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101)
#118    Element.updateChild (package:flutter/src/widgets/framework.dart:2904)
#119    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961)
#120    Element.rebuild (package:flutter/src/widgets/framework.dart:3738)
#121    StatelessElement.update (package:flutter/src/widgets/framework.dart:4016)
#122    Element.updateChild (package:flutter/src/widgets/framework.dart:2893)
#123    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961)
#124    Element.rebuild (package:flutter/src/widgets/framework.dart:3738)
#125    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2348)
#126    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:760)
#127    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:280)
#128    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1033)
#129    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:975)
#130    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:891)
#131    _rootRun (dart:async/zone.dart:1124)
#132    _CustomZone.run (dart:async/zone.dart:1021)
#133    _CustomZone.runGuarded (dart:async/zone.dart:923)
#134    _invoke (dart:ui/hooks.dart:249)
#135    _drawFrame (dart:ui/hooks.dart:207)

**Comment by CarGuo** [comment]
flutter_markdown 的内部解析问题

**Comment by CarGuo** [comment]
dev_next 分支 ，Flutter SDK 1.12.13 版本已经修复
