### ISSUE TITLE
[!] No podspec found for `Flutter` in `.symlinks/flutter/ios`

### ISSUE THREAD

**Issue by semnyqu** [CarGuo/gsy_github_app_flutter#582]
运行环境：
MacOS 10.15.1
Xcode 11.2.1
前期配置都OK了，进入 ./gsy_github_app_flutter/ios/ 路径 发现有pod依赖，执行如下命令：
$ pod install
提示信息如下：
Analyzing dependencies
[!] No podspec found for `Flutter` in `.symlinks/flutter/ios`
去找了相关文件路径，发现.symlinks/flutter/这个文件夹下面不存在iOS文件夹
尝试了各种操作，暂时没找到有效方案，请指教，谢谢

**Comment by CarGuo** [comment]
你需要先 flutter packages get 安装环境，然后参考 readme

**Comment by semnyqu** [comment]
> 你需要先 flutter packages get 安装环境，然后参考 readme

我基本都操作了，
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v1.12.5, on Mac OS X 10.15.1 19B88, locale zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
[✓] Android Studio (version 3.5)
[!] Connected device
    ! No devices available

packages操作
$flutter packages get
  ╔═══════════════════════════════════════════════════════════════
  ║ A new version of Flutter is available!                                    
  ║ To update to the latest version, run "flutter upgrade".                    
  ╚═══════════════════════════════════════════════════════════════

Running "flutter pub get" in gsy_github_app_flutter...             86.0s

**Comment by semnyqu** [comment]
> 你需要先 flutter packages get 安装环境，然后参考 readme

发现是flutter有版本更新，执行如下
flutter upgrade
找到.symlinks/flutter/ios这个文件夹了
