### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by mr-shitou** [CarGuo/gsy_github_app_flutter#585]
Unsupported operation: Cannot extract a file path from a URI with a query component
 #0      _SimpleUri.toFilePath (dart:core/uri.dart:4709)
#1      new File.fromUri (dart:io/file.dart:265)
#2      MarkdownBuilder._buildImage (package:flutter_markdown/src/builder.dart:358)
#3      MarkdownBuilder.visitElementAfter (package:flutter_markdown/src/builder.dart:288)
#4      Element.accept (package:markdown/src/ast.dart:51)
#5      Element.accept (package:markdown/src/ast.dart:48)
#6      Element.accept (package:markdown/src/ast.dart:48)
#7      MarkdownBuilder.build (package:flutter_markdown/src/builder.dart:139)
#8      _MarkdownWidgetState._parseMarkdown (package:flutter_markdown/src/widget.dart:144)
#9      _MarkdownWidgetState.didChangeDependencies (package:flutter_markdown/src/widget.dart:110)
#10     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4086)
#11     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919)
#12     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101)
#13     Element.updateChild (package:flutter/src/widgets/framework.dart:2904)
#14     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127)
#15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101)
#16     Element.updateChild (package:flutter/src/widgets/framework.dart:2904)
#17     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5134)
#18     Element.updateChild (package:flutter/src/widgets/framework.dart:2893)
#19     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3094)
#20     Element.updateChild (package:flutter/src/widgets/framework.dart:2904)
#21     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127)
#22     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101)
#23     Element.updateChild (package:flutter/src/widgets/framework.dart:2904)
#24     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127)
#25     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101)
#26     Element.updateChild (package:flutter/src/widgets/framework.dart:2904)
#27     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961)
#28     Element.rebuild (package:flutter/src/widgets/framework.dart:3738)
#29     StatelessElement.update (package:flutter/src/widgets/framework.dart:4016)
#30     Element.updateChild (package:flutter/src/widgets/framework.dart:2893)
#31     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5134)
#32     Element.updateChild (package:flutter/src/widgets/framework.dart:2893)
#33     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961)
#34     Element.rebuild (package:flutter/src/widgets/framework.dart:3738)
#35     StatefulElement.update (package:flutter/src/widgets/framework.dart:4120)
#36     Element.updateChild (package:flutter/src/widgets/framework.dart:2893)
#37     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5134)
#38     Element.updateChild (package:flutter/src/widgets/framework.dart:2893)
#39     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961)
#40     Element.rebuild (package:flutter/src/widgets/framework.dart:3738)
#41     StatelessElement.update (package:flutter/src/widgets/framework.dart:4016)
#42     Element.updateChild (package:flutter/src/widgets/framework.dart:2893)
#43     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961)
#44     Element.rebuild (package:flutter/src/widgets/framework.dart:3738)
#45     ProxyElement.update (package:flutter/src/widgets/framework.dart:4254)
#46     Element.updateChild (package:flutter/src/widgets/framework.dart:2893)
#47     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5134)
#48     Element.updateChild (package:flutter/src/widgets/framework.dart:2893)
#49     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5134)
#50     Element.updateChild (package:flutter/src/widgets/framework.dart:2893)
#51     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5134)
#52     Element.updateChild (package:flutter/src/widgets/framework.dart:2893)
#53     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5134)
#54     Element.updateChild (package:flutter/src/widgets/framework.dart:2893)
#55     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961)
#56     Element.rebuild (package:flutter/src/widgets/framework.dart:3738)
#57     StatelessElement.update (package:flutter/src/widgets/framework.dart:4016)
#58     Element.updateChild (package:flutter/src/widgets/framework.dart:2893)
#59     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961)
#60     Element.rebuild (package:flutter/src/widgets/framework.dart:3738)
#61     StatefulElement.update (package:flutter/src/widgets/framework.dart:4120)
#62     Element.updateChild (package:flutter/src/widgets/framework.dart:2893)
#63     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961)
#64     Element.rebuild (package:flutter/src/widgets/framework.dart:3738)
#65     StatefulElement.update (package:flutter/src/widgets/framework.dart:4120)
#66     Element.updateChild (package:flutter/src/widgets/framework.dart:2893)
#67     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961)
#68     Element.rebuild (package:flutter/src/widgets/framework.dart:3738)
#69     ProxyElement.update (package:flutter/src/widgets/framework.dart:4254)
#70     Element.updateChild (package:flutter/src/widgets/framework.dart:2893)
#71     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961)
#72     Element.rebuild (package:flutter/src/widgets/framework.dart:3738)
#73     StatelessElement.update (package:flutter/src/widgets/framework.dart:4016)
#74     Element.updateChild (package:flutter/src/widgets/framework.dart:2893)
#75     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5134)
#76     Element.updateChild (package:flutter/src/widgets/framework.dart:2893)
#77     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5134)
#78     Element.updateChild (package:flutter/src/widgets/framework.dart:2893)
#79     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961)
#80     Element.rebuild (package:flutter/src/widgets/framework.dart:3738)
#81     StatelessElement.update (package:flutter/src/widgets/framework.dart:4016)
#82     Element.updateChild (package:flutter/src/widgets/framework.dart:2893)
#83     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961)
#84     Element.rebuild (package:flutter/src/widgets/framework.dart:3738)
#85     StatelessElement.update (package:flutter/src/widgets/framework.dart:4016)
#86     Element.updateChild (package:flutter/src/widgets/framework.dart:2893)
#87     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961)
#88     Element.rebuild (package:flutter/src/widgets/framework.dart:3738)
#89     StatelessElement.update (package:flutter/src/widgets/framework.dart:4016)
#90     Element.updateChild (package:flutter/src/widgets/framework.dart:2893)
#91     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961)
#92     Element.rebuild (package:flutter/src/widgets/framework.dart:3738)
#93     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2348)
#94     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:760)
#95     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:280)
#96     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1033)
#97     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:975)
#98     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:891)
#99     _rootRun (dart:async/zone.dart:1124)
#100    _CustomZone.run (dart:async/zone.dart:1021)
#101    _CustomZone.runGuarded (dart:async/zone.dart:923)
#102    _invoke (dart:ui/hooks.dart:249)
#103    _drawFrame (dart:ui/hooks.dart:207)

**Comment by CarGuo** [comment]
https://github.com/CarGuo/gsy_github_app_flutter/issues/581
