### ISSUE TITLE
因为 flutter_markdown 编译不通过 

### ISSUE THREAD

**Issue by TangYuanHuan** [CarGuo/gsy_github_app_flutter#587]
我的环境
Flutter 1.9.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision c382b8e990 (4 months ago) • 2019-08-18 15:22:36 -0400
Engine • revision 5540684152
Tools • Dart 2.5.0

报错信息
/flutter_markdown-0.3.1/lib/src/style_sheet.dart:123:49: Error: Getter not found: 'link'.
      a: const TextStyle(color: CupertinoColors.link),

flutter_markdown-0.3.1/lib/src/style_sheet.dart:126:42: Error: Getter not found: 'systemGrey6'.
        backgroundColor: CupertinoColors.systemGrey6,

flutter_markdown-0.3.1/lib/src/style_sheet.dart:168:59: Error: Getter not found: 'separator'.
      tableBorder: TableBorder.all(color: CupertinoColors.separator, width: 0),
等等
好像 flutter_markdown这一个插件在https://pub.dev/flutter已经搜索不到

**Comment by CarGuo** [comment]
你把flutter_markdowb .的 ^去掉，我应该只用到0.3.0

**Comment by TangYuanHuan** [comment]
> 你把flutter_markdowb .的 ^去掉，我应该只用到0.3.0

已经编译通过并运行起来，谢谢
