### ISSUE TITLE
想请教大佬一个问题，新建Flutter项目有必要使用AndroidX吗？

### ISSUE THREAD

**Issue by GanZhiXiong** [CarGuo/gsy_github_app_flutter#588]
![image](https://user-images.githubusercontent.com/27394631/70038310-fe3e8300-15f2-11ea-976d-94dc8921748e.png)

大佬，我在Android Studio里面我更新了Flutter插件，新建Flutter项目的时候多了AndroidX的勾选，请问要不要勾选呢，如果勾选了使用AndroidX，那么没有迁移到AndroidX的插件能不能使用呢？

**Comment by CarGuo** [comment]
大致情况应该是这样的：
1、如果你不选 Androidx ，那带 Androidx 的插件你会用不了。
2、如果你选了 Androidx，那不是 Androidx 的插件你可以兼容运行。

**Comment by GanZhiXiong** [comment]
> 2、如果你选了 Androidx，那不是 Androidx 的插件你可以兼容运行。

大佬，这句话，没听明白，您是说选了AndroidX，使用android.support的插件，也能使用吗？

**Comment by CarGuo** [comment]
可以的，我现在就是这么用的，如果遇上插件的 support ，只要保存对应的 androidx 你也导入了，然后打包时用 enableJetifier 就可以了
