### ISSUE TITLE
构建错误

### ISSUE THREAD

**Issue by shizhongyu** [CarGuo/gsy_github_app_flutter#595]
Resolving dependencies...
Running Gradle task 'assembleDebug'...

Compiler message:
../../flutter_windows_v1.9.1+hotfix.6-stable/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_markdown-0.3.1/lib/src/style_sheet.dart:123:49: Error: Getter not found: 'link'.
      a: const TextStyle(color: CupertinoColors.link),
                                                ^^^^
../../flutter_windows_v1.9.1+hotfix.6-stable/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_markdown-0.3.1/lib/src/style_sheet.dart:126:42: Error: Getter not found: 'systemGrey6'.
        backgroundColor: CupertinoColors.systemGrey6,
                                         ^^^^^^^^^^^
../../flutter_windows_v1.9.1+hotfix.6-stable/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_markdown-0.3.1/lib/src/style_sheet.dart:168:59: Error: Getter not found: 'separator'.
      tableBorder: TableBorder.all(color: CupertinoColors.separator, width: 0),
                                                          ^^^^^^^^^
../../flutter_windows_v1.9.1+hotfix.6-stable/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_markdown-0.3.1/lib/src/style_sheet.dart:171:66: Error: Getter not found: 'systemGrey6'.
      tableCellsDecoration: BoxDecoration(color: CupertinoColors.systemGrey6),
                                                                 ^^^^^^^^^^^
../../flutter_windows_v1.9.1+hotfix.6-stable/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_markdown-0.3.1/lib/src/style_sheet.dart:174:32: Error: Getter not found: 'systemGrey6'.
        color: CupertinoColors.systemGrey6,
                               ^^^^^^^^^^^
../../flutter_windows_v1.9.1+hotfix.6-stable/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_markdown-0.3.1/lib/src/style_sheet.dart:177:36: Error: Getter not found: 'systemGrey4'.
            color: CupertinoColors.systemGrey4,
                                   ^^^^^^^^^^^
../../flutter_windows_v1.9.1+hotfix.6-stable/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_markdown-0.3.1/lib/src/style_sheet.dart:184:32: Error: Getter not found: 'systemGrey6'.
        color: CupertinoColors.systemGrey6,
                               ^^^^^^^^^^^
../../flutter_windows_v1.9.1+hotfix.6-stable/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_markdown-0.3.1/lib/src/style_sheet.dart:189:36: Error: Getter not found: 'systemGrey4'.
            color: CupertinoColors.systemGrey4,
                                   ^^^^^^^^^^^
Compiler failed on C:\Flutter\Flutter-start\GSYGithubAppFlutter\lib\main.dart

FAILURE: Build failed with an exception.

* Where:
Script 'C:\Flutter\flutter_windows_v1.9.1+hotfix.6-stable\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 765

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebugArm64'.
> Process 'command 'C:\Flutter\flutter_windows_v1.9.1+hotfix.6-stable\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

**Comment by CarGuo** [comment]
flutter_markdown 应该是0.3.0
