### ISSUE TITLE
想请教大佬一个问题，想实现看小说那种书籍翻页动画，是个什么思路

### ISSUE THREAD

**Issue by YinRenjie1993** [CarGuo/gsy_github_app_flutter#599]
求大佬给点思路

**Comment by CarGuo** [comment]
https://pub.flutter-io.cn/packages/flip_panel 参考下这个

**Comment by YinRenjie1993** [comment]
比这个复杂多了吧。

**Comment by CarGuo** [comment]
https://github.com/CarGuo/gsy_flutter_demo/tree/master/lib/widget/book_page

**Comment by CarGuo** [comment]
https://github.com/CarGuo/gsy_flutter_demo/tree/master/lib/widget/book_page

**Comment by lwlizhe** [comment]
这么说吧……如果你想实现的是第二个gif的效果…… 

https://juejin.im/pin/5dd68b805188250b3a065be6

思路这块，这个按照 https://github.com/AnliaLee/BookPage 和介绍的相关文章来走一遍就差不多了

但是坑还是要踩的，而且记得还不少……

顺便提一下，这些坑，有点……怪，比如说，很奇怪的是，在Android原生上覆盖绘制比裁剪绘制性能差很多，但是在flutter上正好反过来……裁剪比覆盖性能差很多(具体原因不明……不知道最新版本有没有改善，有兴趣可以试验下)……而且flutter官方确实也提到了，阴影这块属于性能很差的部分，所以有些地方需要考虑如何减少阴影的绘制范围，以及替代阴影方案的实现……

再提一点……将picture转为image并绘制有奇效，但是我这转为image之后文字会有毛边，不知道是不是我这的问题……

**Comment by CarGuo** [comment]
@lwlizhe https://github.com/CarGuo/gsy_flutter_demo/tree/master/lib/widget/book_page 目前我写了个简单的 demo ，但是在文字的方面用了另外的实现方式，感觉还是不够好。

**Comment by YinRenjie1993** [comment]
@lwlizhe 大佬666啊 这个动画可以开源不

**Comment by lwlizhe** [comment]
> @lwlizhe 大佬666啊 这个动画可以开源不 想码个flutter版阅读 基本功能完成了

额，还在私人库(https://github.com/lwlizhe/flutter_novel)，打算做成一个仿追书神器APP再开源出去……提前打个预防针，我开发看缘分的……只能说尽快搞出来……最基本的功能现在还差书评、简介、书库这几块……像书城、缓存下载、阅读页面和菜单都差不多了。

**Comment by YinRenjie1993** [comment]
@lwlizhe 老哥加个好友啊

**Comment by lwlizhe** [comment]
> @lwlizhe 老哥加个好友啊 丢个联系方式啊

我掘金也是这个账号，你关注下呗，弄出来我会发个沸点或者文章的

**Comment by YinRenjie1993** [comment]
@lwlizhe 关注了 加个微信 qq 或者钉钉啥的啊

**Comment by lwlizhe** [comment]
> @lwlizhe 关注了 加个微信 qq 或者钉钉啥的啊

额……这个不太方便……QQ微信什么的还是私人号，哪天我搞个小号过来……

**Comment by YinRenjie1993** [comment]
@CarGuo 老哥 有空完善完善啊

**Comment by YinRenjie1993** [comment]
@lwlizhe 那个矩阵算法可以分享下dart的实现吗 数学不好 不知道咋翻译

**Comment by lwlizhe** [comment]
> @lwlizhe 那个矩阵算法可以分享下dart的实现吗 数学不好 不知道咋翻译

矩阵就多了一个维度，没啥影响的……多出来的那部分维度填0就行了，矩阵都提供了足够你使用的api的

```
    canvas.translate(mBezierControl1.dx, mBezierControl1.dy);

    /// 矩阵公式：α表示翻转页面和边的夹角
    /// https://juejin.im/post/5a32ade0f265da43252954b2
    ///
    ///  -(1-2sin(a)^2 )   2sin(a)cos(a)   0
    ///  2sin(a)cos(a)      1-2sin(a)^2    0
    ///  0                0             1

    double dis = math.sqrt(math.pow((mCornerX - mBezierControl1.dx), 2) +
        math.pow((mBezierControl2.dy - mCornerY), 2));
    double sinAngle = (mCornerX - mBezierControl1.dx) / dis;
    double cosAngle = (mBezierControl2.dy - mCornerY) / dis;

    Matrix4 matrix4 = Matrix4.columns(
        v.Vector4(
            -(1 - 2 * sinAngle * sinAngle), 2 * sinAngle * cosAngle, 0, 0),
        v.Vector4(2 * sinAngle * cosAngle, (1 - 2 * sinAngle * sinAngle), 0, 0),
        v.Vector4(0, 0, 1, 0),
        v.Vector4(0, 0, 0, 1));

    matrix4.translate(-mBezierControl1.dx, -mBezierControl1.dy);
    canvas.transform(matrix4.storage);
```

**Comment by CarGuo** [comment]
@lwlizhe 如下 GIF 所示，已经进行了优化，实现了文章中 90%的逻辑，虽然还有一些 bug

![tttt](https://user-images.githubusercontent.com/10770362/71076640-097fda00-21c1-11ea-8a96-fad4c1dd3d45.gif)

**Comment by lwlizhe** [comment]
> @lwlizhe 如下 GIF 所示，已经进行了优化，实现了文章中 90%的逻辑，虽然还有一些 bug
> 
> ![tttt](https://user-images.githubusercontent.com/10770362/71076640-097fda00-21c1-11ea-8a96-fad4c1dd3d45.gif)

大佬牛啤！当初我搞这个搞了好长时间……

**Comment by YinRenjie1993** [comment]
@CarGuo 牛逼牛逼 我搞那个阴影 一直旋转角度不对
