### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by theecn** [CarGuo/gsy_github_app_flutter#603]
Unsupported operation: Cannot extract a file path from a URI with a query component
 #0      _SimpleUri.toFilePath (dart:core/uri.dart:4709:9)
#1      new File.fromUri (dart:io/file.dart:265:49)
#2      MarkdownBuilder._buildImage (package:flutter_markdown/src/builder.dart:358:33)
#3      MarkdownBuilder.visitElementAfter (package:flutter_markdown/src/builder.dart:288:30)
#4      Element.accept (package:markdown/src/ast.dart:51:15)
#5      Element.accept (package:markdown/src/ast.dart:48:17)
#6      Element.accept (package:markdown/src/ast.dart:48:17)
#7      MarkdownBuilder.build (package:flutter_markdown/src/builder.dart:139:12)
#8      _MarkdownWidgetState._parseMarkdown (package:flutter_markdown/src/widget.dart:144:25)
#9      _MarkdownWidgetState.didChangeDependencies (package:flutter_markdown/src/widget.dart:110:5)
#10     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4086:12)
#11     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
#12     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
#13     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
#14     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
#15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
#16     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
#17     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
#18     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
#19     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
#20     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
#21     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
#22     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
#23     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
#24     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
#25     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
#26     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
#27     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
#28     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
#29     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
#30     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
#31     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
#32     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
#33     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
#34     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
#35     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
#36     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
#37     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
#38     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4088:11)
#39     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
#40     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
#41     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
#42     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
#43     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
#44     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
#45     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
#46     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
#47     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
#48     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
#49     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
#50     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
#51     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
#52     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
#53     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
#54     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
#55     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
#56     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
#57     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
#58     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
#59     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
#60     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
#61     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
#62     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
#63     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
#64     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
#65     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
#66     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
#67     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
#68     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
#69     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
#70     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
#71     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
#72     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
#73     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
#74     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
#75     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
#76     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
#77     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
#78     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4088:11)
#79     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
#80     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
#81     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
#82     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
#83     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
#84     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
#85     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4088:11)
#86     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
#87     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
#88     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
#89     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
#90     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
#91     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
#92     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
#93     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
#94     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
#95     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
#96     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
#97     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
#98     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
#99     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
#100    Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
#101    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
#102    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
#103    Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
#104    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
#105    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
#106    Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
#107    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
#108    Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
#109    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
#110    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
#111    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
#112    Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
#113    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
#114    Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
#115    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
#116    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
#117    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
#118    Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
#119    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
#120    Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
#121    StatelessElement.update (package:flutter/src/widgets/framework.dart:4016:5)
#122    Element.updateChild (package:flutter/src/widgets/framework.dart:2893:15)
#123    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
#124    Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
#125    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2348:33)
#126    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:760:20)
#127    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:280:5)
#128    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1033:15)
#129    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:975:9)
#130    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:891:5)
#131    _rootRun (dart:async/zone.dart:1124:13)
#132    _CustomZone.run (dart:async/zone.dart:1021:19)
#133    _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#134    _invoke (dart:ui/hooks.dart:249:10)
#135    _drawFrame (dart:ui/hooks.dart:207:3)

**Comment by CarGuo** [comment]
dev_next flutter 1.12.13 版本已经修复
