### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by daofeng2015** [CarGuo/gsy_github_app_flutter#606]
RangeError (length): Invalid value: Valid value range is empty: 0
 #0      MarkdownBuilder.visitElementAfter (package:flutter_markdown/src/builder.dart:0)
#1      Element.accept (package:markdown/src/ast.dart:51)
#2      Element.accept (package:markdown/src/ast.dart:48)
#3      MarkdownBuilder.build (package:flutter_markdown/src/builder.dart:139)
#4      _MarkdownWidgetState._parseMarkdown (package:flutter_markdown/src/widget.dart:144)
#5      _MarkdownWidgetState.didChangeDependencies (package:flutter_markdown/src/widget.dart:110)
#6      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4086)
#7      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919)
#8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101)
#9      Element.updateChild (package:flutter/src/widgets/framework.dart:2904)
#10     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127)
#11     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101)
#12     Element.updateChild (package:flutter/src/widgets/framework.dart:2904)
#13     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5134)
#14     Element.updateChild (package:flutter/src/widgets/framework.dart:2893)
#15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3094)
#16     Element.updateChild (package:flutter/src/widgets/framework.dart:2904)
#17     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127)
#18     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101)
#19     Element.updateChild (package:flutter/src/widgets/framework.dart:2904)
#20     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127)
#21     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101)
#22     Element.updateChild (package:flutter/src/widgets/framework.dart:2904)
#23     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961)
#24     Element.rebuild (package:flutter/src/widgets/framework.dart:3738)
#25     StatelessElement.update (package:flutter/src/widgets/framework.dart:4016)
#26     Element.updateChild (package:flutter/src/widgets/framework.dart:2893)
#27     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5134)
#28     Element.updateChild (package:flutter/src/widgets/framework.dart:2893)
#29     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961)
#30     Element.rebuild (package:flutter/src/widgets/framework.dart:3738)
#31     StatefulElement.update (package:flutter/src/widgets/framework.dart:4120)
#32     Element.updateChild (package:flutter/src/widgets/framework.dart:2893)
#33     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5134)
#34     Element.updateChild (package:flutter/src/widgets/framework.dart:2893)
#35     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961)
#36     Element.rebuild (package:flutter/src/widgets/framework.dart:3738)
#37     StatelessElement.update (package:flutter/src/widgets/framework.dart:4016)
#38     Element.updateChild (package:flutter/src/widgets/framework.dart:2893)
#39     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961)
#40     Element.rebuild (package:flutter/src/widgets/framework.dart:3738)
#41     ProxyElement.update (package:flutter/src/widgets/framework.dart:4254)
#42     Element.updateChild (package:flutter/src/widgets/framework.dart:2893)
#43     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5134)
#44     Element.updateChild (package:flutter/src/widgets/framework.dart:2893)
#45     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5134)
#46     Element.updateChild (package:flutter/src/widgets/framework.dart:2893)
#47     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5134)
#48     Element.updateChild (package:flutter/src/widgets/framework.dart:2893)
#49     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5134)
#50     Element.updateChild (package:flutter/src/widgets/framework.dart:2893)
#51     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961)
#52     Element.rebuild (package:flutter/src/widgets/framework.dart:3738)
#53     StatelessElement.update (package:flutter/src/widgets/framework.dart:4016)
#54     Element.updateChild (package:flutter/src/widgets/framework.dart:2893)
#55     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961)
#56     Element.rebuild (package:flutter/src/widgets/framework.dart:3738)
#57     StatefulElement.update (package:flutter/src/widgets/framework.dart:4120)
#58     Element.updateChild (package:flutter/src/widgets/framework.dart:2893)
#59     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961)
#60     Element.rebuild (package:flutter/src/widgets/framework.dart:3738)
#61     StatefulElement.update (package:flutter/src/widgets/framework.dart:4120)
#62     Element.updateChild (package:flutter/src/widgets/framework.dart:2893)
#63     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961)
#64     Element.rebuild (package:flutter/src/widgets/framework.dart:3738)
#65     ProxyElement.update (package:flutter/src/widgets/framework.dart:4254)
#66     Element.updateChild (package:flutter/src/widgets/framework.dart:2893)
#67     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961)
#68     Element.rebuild (package:flutter/src/widgets/framework.dart:3738)
#69     StatelessElement.update (package:flutter/src/widgets/framework.dart:4016)
#70     Element.updateChild (package:flutter/src/widgets/framework.dart:2893)
#71     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5134)
#72     Element.updateChild (package:flutter/src/widgets/framework.dart:2893)
#73     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5134)
#74     Element.updateChild (package:flutter/src/widgets/framework.dart:2893)
#75     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961)
#76     Element.rebuild (package:flutter/src/widgets/framework.dart:3738)
#77     StatelessElement.update (package:flutter/src/widgets/framework.dart:4016)
#78     Element.updateChild (package:flutter/src/widgets/framework.dart:2893)
#79     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961)
#80     Element.rebuild (package:flutter/src/widgets/framework.dart:3738)
#81     StatelessElement.update (package:flutter/src/widgets/framework.dart:4016)
#82     Element.updateChild (package:flutter/src/widgets/framework.dart:2893)
#83     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961)
#84     Element.rebuild (package:flutter/src/widgets/framework.dart:3738)
#85     StatelessElement.update (package:flutter/src/widgets/framework.dart:4016)
#86     Element.updateChild (package:flutter/src/widgets/framework.dart:2893)
#87     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961)
#88     Element.rebuild (package:flutter/src/widgets/framework.dart:3738)
#89     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2348)
#90     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:760)
#91     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:280)
#92     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1033)
#93     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:975)
#94     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:891)
#95     _rootRun (dart:async/zone.dart:1124)
#96     _CustomZone.run (dart:async/zone.dart:1021)
#97     _CustomZone.runGuarded (dart:async/zone.dart:923)
#98     _invoke (dart:ui/hooks.dart:249)
#99     _drawFrame (dart:ui/hooks.dart:207)

**Comment by CarGuo** [comment]
https://github.com/CarGuo/gsy_github_app_flutter/issues/581
