### ISSUE TITLE
error: 'NetworkCacheImage.load' ('ImageStreamCompleter Function(NetworkCacheImage)') isn't a valid override of 'ImageProvider.load' ('ImageStreamCompleter Function(NetworkCacheImage, Future<Codec> Function(Uint8List, {cacheHeight: int, cacheWidth: int}))'). (invalid_override at [gsy_github_app_flutter] lib/widget/network_cache_image.dart:37)

### ISSUE THREAD

**Issue by HDHunter** [CarGuo/gsy_github_app_flutter#608]
bogon:gsy_github_app_flutter yodo1$ flutter --version
Flutter 1.12.13+hotfix.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 27321ebbad (2 weeks ago) • 2019-12-10 18:15:01 -0800
Engine • revision 2994f7e1e6
Tools • Dart 2.7.0
bogon:gsy_github_app_flutter yodo1$ 

![image](https://user-images.githubusercontent.com/12092336/71433881-a2ac7480-271c-11ea-8e98-5f2f0f824a81.png)

使用 stable 最新版本flutter编译，出现一个方法复写语法错误。弟兄们有见过的吗？

**Comment by CarGuo** [comment]
请看 readme，现在支持的版本是 1.9 的

**Comment by HDHunter** [comment]
> 请看 readme，现在支持的版本是 1.9 的

yes，切换过来

 flutter version v1.9.1+hotfix.4   已经没问题了。

**Comment by erperejildo** [comment]
hi @HDHunter, sorry for the off-topic but do you know how to listen to the rewarded videos? I can show everything but I don't know how to listen to onAdverRewardEarned in order to detect from Flutter if the user watched the video or no
