### ISSUE TITLE
登录接口报错，今天上午还可以登录成功，下午就不行了

### ISSUE THREAD

**Issue by Ivan5201314** [CarGuo/gsy_github_app_flutter#614]
lutter: base64Str login SXZhbjUyMDEyMTQ6RG9uZzEzNTI4OA==
flutter: 请求url：https://api.github.com/authorizations
flutter: 请求头: {content-type: application/json; charset=utf-8, Authorization: Basic SXZhbjUyMDEyMTQ6RG9uZzEzNTI4OA==}
flutter: 请求参数: {"scopes":["user","repo","gist","notifications"],"note":"admin_script"}
flutter: type 'String' is not a subtype of type 'Map<String, dynamic>'
flutter: 请求异常: DioError [DioErrorType.RESPONSE]: Http status error [401]
flutter: 请求异常信息: {"message":"Bad credentials","documentation_url":"https://developer.github.com/v3"}

**Comment by CarGuo** [comment]
这么奇怪？换个网络环境试试记得用用户名和密码，不要用邮箱

**Comment by CarGuo** [comment]
登陆有适合和 github 自己的 api 有关，目前已经增加的登陆支持
