### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by CourteousBin** [CarGuo/gsy_github_app_flutter#617]
'package:flutter/src/widgets/media_query.dart': Failed assertion: line 626 pos 15: 'child != null': is not true.
 #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:42:39)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:38:5)
#2      new MediaQuery (package:flutter/src/widgets/media_query.dart:626:15)
#3      new MediaQuery.removePadding (package:flutter/src/widgets/media_query.dart:665:12)
#4      SafeArea.build (package:flutter/src/widgets/safe_area.dart:110:25)
#5      StatelessElement.build (package:flutter/src/widgets/framework.dart:4291:28)
#6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4223:15)
#7      Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#8      StatelessElement.update (package:flutter/src/widgets/framework.dart:4298:5)
#9      Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
#10     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
#11     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
#12     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
#13     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
#14     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#15     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#16     StatelessElement.update (package:flutter/src/widgets/framework.dart:4298:5)
#17     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
#18     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#19     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#20     StatelessElement.update (package:flutter/src/widgets/framework.dart:4298:5)
#21     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
#22     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#23     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#24     ProxyElement.update (package:flutter/src/widgets/framework.dart:4557:5)
#25     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
#26     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#27     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#28     ProxyElement.update (package:flutter/src/widgets/framework.dart:4557:5)
#29     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
#30     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5161:32)
#31     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5561:17)
#32     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
#33     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#34     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#35     StatefulElement.update (package:flutter/src/widgets/framework.dart:4413:5)
#36     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
#37     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#38     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#39     ProxyElement.update (package:flutter/src/widgets/framework.dart:4557:5)
#40     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
#41     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#42     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#43     StatefulElement.update (package:flutter/src/widgets/framework.dart:4413:5)
#44     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
#45     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
#46     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
#47     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#48     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#49     StatelessElement.update (package:flutter/src/widgets/framework.dart:4298:5)
#50     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
#51     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
#52     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
#53     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#54     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#55     StatefulElement.update (package:flutter/src/widgets/framework.dart:4413:5)
#56     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
#57     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#58     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#59     StatefulElement.update (package:flutter/src/widgets/framework.dart:4413:5)
#60     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
#61     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#62     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#63     ProxyElement.update (package:flutter/src/widgets/framework.dart:4557:5)
#64     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
#65     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#66     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#67     ProxyElement.update (package:flutter/src/widgets/framework.dart:4557:5)
#68     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
#69     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#70     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#71     StatefulElement.update (package:flutter/src/widgets/framework.dart:4413:5)
#72     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
#73     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
#74     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
#75     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#76     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#77     StatelessElement.update (package:flutter/src/widgets/framework.dart:4298:5)
#78     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
#79     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
#80     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
#81     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#82     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#83     StatefulElement.update (package:flutter/src/widgets/framework.dart:4413:5)
#84     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
#85     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#86     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#87     StatelessElement.update (package:flutter/src/widgets/framework.dart:4298:5)
#88     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
#89     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#90     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#91     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2432:33)
#92     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:773:20)
#93     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:283:5)
#94     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1102:15)
#95     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1041:9)
#96     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:957:5)
#97     _rootRun (dart:async/zone.dart:1126:13)
#98     _CustomZone.run (dart:async/zone.dart:1023:19)
#99     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#100    _invoke (dart:ui/hooks.dart:259:10)
#101    _drawFrame (dart:ui/hooks.dart:217:3)

**Comment by CarGuo** [comment]
想请问下这是什么情况下出现的？
