### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by YaoHooHoo** [CarGuo/gsy_github_app_flutter#618]
Unsupported operation: Cannot extract a file path from a URI with a query component
 #0      _SimpleUri.toFilePath (dart:core/uri.dart:4711:9)
#1      new File.fromUri (dart:io/file.dart:267:49)
#2      kDefaultImageBuilder.<anonymous closure> (package:flutter_markdown/src/_functions_io.dart:33:30)
#3      MarkdownBuilder._buildImage (package:flutter_markdown/src/builder.dart:364:35)
#4      MarkdownBuilder.visitElementAfter (package:flutter_markdown/src/builder.dart:306:30)
#5      Element.accept (package:markdown/src/ast.dart:51:15)
#6      Element.accept (package:markdown/src/ast.dart:48:17)
#7      Element.accept (package:markdown/src/ast.dart:48:17)
#8      MarkdownBuilder.build (package:flutter_markdown/src/builder.dart:150:12)
#9      _MarkdownWidgetState._parseMarkdown (package:flutter_markdown/src/widget.dart:175:25)
#10     _MarkdownWidgetState.didChangeDependencies (package:flutter_markdown/src/widget.dart:136:5)
#11     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4376:12)
#12     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
#13     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#14     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#15     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
#16     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#17     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#18     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
#19     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#20     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#21     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
#22     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#23     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#24     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
#25     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#26     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#27     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#28     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#29     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
#30     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
#31     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#32     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#33     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
#34     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#35     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#36     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#37     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#38     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
#39     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4381:11)
#40     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
#41     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#42     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#43     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
#44     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#45     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#46     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#47     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#48     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
#49     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
#50     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#51     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#52     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#53     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#54     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
#55     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
#56     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#57     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#58     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
#59     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#60     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#61     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
#62     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#63     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#64     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
#65     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#66     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#67     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
#68     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#69     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#70     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#71     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#72     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
#73     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
#74     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#75     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#76     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#77     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#78     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
#79     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4381:11)
#80     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
#81     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#82     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#83     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#84     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#85     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
#86     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4381:11)
#87     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
#88     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#89     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#90     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#91     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#92     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
#93     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
#94     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#95     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#96     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#97     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#98     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
#99     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
#100    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#101    Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#102    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
#103    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#104    Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#105    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
#106    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#107    Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#108    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#109    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#110    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
#111    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
#112    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#113    Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#114    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#115    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#116    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
#117    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
#118    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#119    Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#120    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#121    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#122    StatelessElement.update (package:flutter/src/widgets/framework.dart:4298:5)
#123    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
#124    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#125    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#126    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2432:33)
#127    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:773:20)
#128    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:283:5)
#129    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1102:15)
#130    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1041:9)
#131    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:957:5)
#132    _rootRun (dart:async/zone.dart:1126:13)
#133    _CustomZone.run (dart:async/zone.dart:1023:19)
#134    _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#135    _invoke (dart:ui/hooks.dart:259:10)
#136    _drawFrame (dart:ui/hooks.dart:217:3)

**Comment by CarGuo** [comment]
https://github.com/CarGuo/gsy_github_app_flutter/issues/581
