### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by LonelyDreamr** [CarGuo/gsy_github_app_flutter#636]
Unsupported operation: Cannot extract a file path from a URI with a query component
 #0      _SimpleUri.toFilePath (dart:core/uri.dart:4709)
#1      new File.fromUri (dart:io/file.dart:265)
#2      MarkdownBuilder._buildImage (package:flutter_markdown/src/builder.dart:358)
#3      MarkdownBuilder.visitElementAfter (package:flutter_markdown/src/builder.dart:288)
#4      Element.accept (package:markdown/src/ast.dart:51)
#5      Element.accept (package:markdown/src/ast.dart:48)
#6      Element.accept (package:markdown/src/ast.dart:48)
#7      Element.accept (package:markdown/src/ast.dart:48)
#8      Element.accept (package:markdown/src/ast.dart:48)
#9      MarkdownBuilder.build (package:flutter_markdown/src/builder.dart:139)
#10     _MarkdownWidgetState._parseMarkdown (package:flutter_markdown/src/widget.dart:144)
#11     _MarkdownWidgetState.didChangeDependencies (package:flutter_markdown/src/widget.dart:110)
#12     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4086)
#13     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919)
#14     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101)
#15     Element.updateChild (package:flutter/src/widgets/framework.dart:2904)
#16     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127)
#17     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101)
#18     Element.updateChild (package:flutter/src/widgets/framework.dart:2904)
#19     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127)
#20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101)
#21     Element.updateChild (package:flutter/src/widgets/framework.dart:2904)
#22     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127)
#23     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101)
#24     Element.updateChild (package:flutter/src/widgets/framework.dart:2904)
#25     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127)
#26     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101)
#27     Element.updateChild (package:flutter/src/widgets/framework.dart:2904)
#28     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961)
#29     Element.rebuild (package:flutter/src/widgets/framework.dart:3738)
#30     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924)
#31     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919)
#32     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101)
#33     Element.updateChild (package:flutter/src/widgets/framework.dart:2904)
#34     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127)
#35     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101)
#36     Element.updateChild (package:flutter/src/widgets/framework.dart:2904)
#37     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961)
#38     Element.rebuild (package:flutter/src/widgets/framework.dart:3738)
#39     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924)
#40     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4088)
#41     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919)
#42     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101)
#43     Element.updateChild (package:flutter/src/widgets/framework.dart:2904)
#44     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127)
#45     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101)
#46     Element.updateChild (package:flutter/src/widgets/framework.dart:2904)
#47     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961)
#48     Element.rebuild (package:flutter/src/widgets/framework.dart:3738)
#49     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924)
#50     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919)
#51     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101)
#52     Element.updateChild (package:flutter/src/widgets/framework.dart:2904)
#53     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961)
#54     Element.rebuild (package:flutter/src/widgets/framework.dart:3738)
#55     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924)
#56     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919)
#57     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101)
#58     Element.updateChild (package:flutter/src/widgets/framework.dart:2904)
#59     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127)
#60     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101)
#61     Element.updateChild (package:flutter/src/widgets/framework.dart:2904)
#62     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127)
#63     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101)
#64     Element.updateChild (package:flutter/src/widgets/framework.dart:2904)
#65     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127)
#66     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101)
#67     Element.updateChild (package:flutter/src/widgets/framework.dart:2904)
#68     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127)
#69     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101)
#70     Element.updateChild (package:flutter/src/widgets/framework.dart:2904)
#71     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961)
#72     Element.rebuild (package:flutter/src/widgets/framework.dart:3738)
#73     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924)
#74     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919)
#75     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101)
#76     Element.updateChild (package:flutter/src/widgets/framework.dart:2904)
#77     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961)
#78     Element.rebuild (package:flutter/src/widgets/framework.dart:3738)
#79     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924)
#80     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4088)
#81     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919)
#82     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101)
#83     Element.updateChild (package:flutter/src/widgets/framework.dart:2904)
#84     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961)
#85     Element.rebuild (package:flutter/src/widgets/framework.dart:3738)
#86     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924)
#87     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4088)
#88     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919)
#89     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101)
#90     Element.updateChild (package:flutter/src/widgets/framework.dart:2904)
#91     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961)
#92     Element.rebuild (package:flutter/src/widgets/framework.dart:3738)
#93     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924)
#94     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919)
#95     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101)
#96     Element.updateChild (package:flutter/src/widgets/framework.dart:2904)
#97     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961)
#98     Element.rebuild (package:flutter/src/widgets/framework.dart:3738)
#99     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924)
#100    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919)
#101    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101)
#102    Element.updateChild (package:flutter/src/widgets/framework.dart:2904)
#103    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127)
#104    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101)
#105    Element.updateChild (package:flutter/src/widgets/framework.dart:2904)
#106    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127)
#107    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101)
#108    Element.updateChild (package:flutter/src/widgets/framework.dart:2904)
#109    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961)
#110    Element.rebuild (package:flutter/src/widgets/framework.dart:3738)
#111    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924)
#112    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919)
#113    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101)
#114    Element.updateChild (package:flutter/src/widgets/framework.dart:2904)
#115    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961)
#116    Element.rebuild (package:flutter/src/widgets/framework.dart:3738)
#117    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924)
#118    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919)
#119    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101)
#120    Element.updateChild (package:flutter/src/widgets/framework.dart:2904)
#121    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961)
#122    Element.rebuild (package:flutter/src/widgets/framework.dart:3738)
#123    StatelessElement.update (package:flutter/src/widgets/framework.dart:4016)
#124    Element.updateChild (package:flutter/src/widgets/framework.dart:2893)
#125    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961)
#126    Element.rebuild (package:flutter/src/widgets/framework.dart:3738)
#127    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2348)
#128    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:760)
#129    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:280)
#130    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1033)
#131    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:975)
#132    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:891)
#133    _rootRun (dart:async/zone.dart:1124)
#134    _CustomZone.run (dart:async/zone.dart:1021)
#135    _CustomZone.runGuarded (dart:async/zone.dart:923)
#136    _invoke (dart:ui/hooks.dart:249)
#137    _drawFrame (dart:ui/hooks.dart:207)

**Comment by CarGuo** [comment]
https://github.com/CarGuo/gsy_github_app_flutter/issues/581
