### ISSUE TITLE
底部栏目切换慢

### ISSUE THREAD

**Issue by martenorton** [CarGuo/gsy_github_app_flutter#638]
底部动态-趋势-我的，这几个栏目点击的时候，切换速度慢，滑动切换速度还可以

**Comment by CarGuo** [comment]
默认下 TabBar + PageView 是这样的效果的

**Comment by martenorton** [comment]
这个不能优化一下？使用频率超高的地方，这样卡顿的体验不好。

**Comment by CarGuo** [comment]
release 模式下还好，主要是因为增加了双击刷新的功能导致的

**Comment by Liberations** [comment]
gsy_tabs.dart 中的onDoubleTap 注释掉效果会好一点，onDoubleTap 判断有500MS的延时

**Comment by CarGuo** [comment]
是的，这个是我这边加的
