### ISSUE TITLE
有一个接口403,具体是什么原因?

### ISSUE THREAD

**Issue by weixianshishen** [CarGuo/gsy_github_app_flutter#646]
I/flutter ( 4905): 请求url：https://api.github.com/users/weixianshishen/received_events?page=1&per_page=20
I/flutter ( 4905): 请求头: {content-type: application/json; charset=utf-8, Authorization: token 2b0e74a3a196976dac7119f0f8e15e2f97b2cabc}
I/flutter ( 4905): 请求异常: DioError [DioErrorType.RESPONSE]: Http status error [**403**]
I/flutter ( 4905): 请求异常信息: {"message":"Resource not accessible by integration","documentation_url":"https://developer.github.com/v3/activity/events/#list-events-that-a-user-has-received"}

**Comment by CarGuo** [comment]
这个我目前测试是正常，是不是授权信息异常？
