### ISSUE TITLE
你好，我发现个现象：从homePage页面中点击某一个按钮，跳转到页面B，此时homePage的didChangeDependencies方法也会再执行。一直想不明白是哪里的问题，楼主空的时候能解答一下这个疑问吗？谢谢啦

### ISSUE THREAD

**Issue by manburenshenglu** [CarGuo/gsy_github_app_flutter#648]
![image](https://user-images.githubusercontent.com/13146756/76049268-0c5cc080-5fa1-11ea-989f-38e914294908.png)

**Comment by CarGuo** [comment]
其中一个原因是因为内部用了 InheritedWidget 相关的，但是我没有做精细的颗粒度管理， InheritedWidget 是会触发这个回调的，在更新共享状态的时候。

**Comment by manburenshenglu** [comment]
谢谢楼主，我全局搜索了一下，好像没有发现使用InheritedWidget的地方啊？

**Comment by CarGuo** [comment]
InheritedWidget 是用于状态或者信息共享的，比如 flutter_redux、scoped_model 、 provider 等插件都用到了。

**Comment by manburenshenglu** [comment]
你好楼主，我现在不想状态共享，该修改哪里的代码呢
