### ISSUE TITLE
Resolving dependencies failed

### ISSUE THREAD

**Issue by naitiynil** [CarGuo/gsy_github_app_flutter#649]
Because gsy_github_app_flutter depends on photo_view from git which requires the Flutter SDK, version solving failed.

Flutter users should run `flutter pub get` instead of `pub get`.

请问这个怎么处理？android studio上面没看到'flutter pub get'选项，只有'pub get'.

**Comment by CarGuo** [comment]
命令行输入 flutter packages get ， 然后还有问题可见 https://github.com/CarGuo/gsy_github_app_flutter/issues/13#issuecomment-496960086
