### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by JevonShi** [CarGuo/gsy_github_app_flutter#651]
'package:flutter/src/services/text_input.dart': Failed assertion: line 846 pos 12: 'attached': is not true.
 #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:42:39)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:38:5)
#2      TextInputConnection.setStyle (package:flutter/src/services/text_input.dart:846:12)
#3      EditableTextState.didUpdateWidget (package:flutter/src/widgets/editable_text.dart:1175:29)
#4      StatefulElement.update (package:flutter/src/widgets/framework.dart:4469:58)
#5      Element.updateChild (package:flutter/src/widgets/framework.dart:3052:15)
#6      SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5525:14)
#7      Element.updateChild (package:flutter/src/widgets/framework.dart:3052:15)
#8      _RenderDecorationElement._updateChild (package:flutter/src/material/input_decorator.dart:1537:30)
#9      _RenderDecorationElement.update (package:flutter/src/material/input_decorator.dart:1553:5)
#10     Element.updateChild (package:flutter/src/widgets/framework.dart:3052:15)
#11     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4316:16)
#12     Element.rebuild (package:flutter/src/widgets/framework.dart:4020:5)
#13     StatefulElement.update (package:flutter/src/widgets/framework.dart:4486:5)
#14     Element.updateChild (package:flutter/src/widgets/framework.dart:3052:15)
#15     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4316:16)
#16     Element.rebuild (package:flutter/src/widgets/framework.dart:4020:5)
#17     StatefulElement.update (package:flutter/src/widgets/framework.dart:4486:5)
#18     Element.updateChild (package:flutter/src/widgets/framework.dart:3052:15)
#19     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5525:14)
#20     Element.updateChild (package:flutter/src/widgets/framework.dart:3052:15)
#21     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4316:16)
#22     Element.rebuild (package:flutter/src/widgets/framework.dart:4020:5)
#23     StatelessElement.update (package:flutter/src/widgets/framework.dart:4371:5)
#24     Element.updateChild (package:flutter/src/widgets/framework.dart:3052:15)
#25     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4316:16)
#26     Element.rebuild (package:flutter/src/widgets/framework.dart:4020:5)
#27     StatefulElement.update (package:flutter/src/widgets/framework.dart:4486:5)
#28     Element.updateChild (package:flutter/src/widgets/framework.dart:3052:15)
#29     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4316:16)
#30     Element.rebuild (package:flutter/src/widgets/framework.dart:4020:5)
#31     StatefulElement.update (package:flutter/src/widgets/framework.dart:4486:5)
#32     Element.updateChild (package:flutter/src/widgets/framework.dart:3052:15)
#33     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5525:14)
#34     Element.updateChild (package:flutter/src/widgets/framework.dart:3052:15)
#35     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4316:16)
#36     Element.rebuild (package:flutter/src/widgets/framework.dart:4020:5)
#37     StatefulElement.update (package:flutter/src/widgets/framework.dart:4486:5)
#38     Element.updateChild (package:flutter/src/widgets/framework.dart:3052:15)
#39     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5525:14)
#40     Element.updateChild (package:flutter/src/widgets/framework.dart:3052:15)
#41     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5525:14)
#42     Element.updateChild (package:flutter/src/widgets/framework.dart:3052:15)
#43     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4316:16)
#44     Element.rebuild (package:flutter/src/widgets/framework.dart:4020:5)
#45     StatefulElement.update (package:flutter/src/widgets/framework.dart:4486:5)
#46     Element.updateChild (package:flutter/src/widgets/framework.dart:3052:15)
#47     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4316:16)
#48     Element.rebuild (package:flutter/src/widgets/framework.dart:4020:5)
#49     StatefulElement.update (package:flutter/src/widgets/framework.dart:4486:5)
#50     Element.updateChild (package:flutter/src/widgets/framework.dart:3052:15)
#51     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5234:32)
#52     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5637:17)
#53     Element.updateChild (package:flutter/src/widgets/framework.dart:3052:15)
#54     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5525:14)
#55     Element.updateChild (package:flutter/src/widgets/framework.dart:3052:15)
#56     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5525:14)
#57     Element.updateChild (package:flutter/src/widgets/framework.dart:3052:15)
#58     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4316:16)
#59     Element.rebuild (package:flutter/src/widgets/framework.dart:4020:5)
#60     ProxyElement.update (package:flutter/src/widgets/framework.dart:4630:5)
#61     Element.updateChild (package:flutter/src/widgets/framework.dart:3052:15)
#62     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4316:16)
#63     Element.rebuild (package:flutter/src/widgets/framework.dart:4020:5)
#64     StatefulElement.update (package:flutter/src/widgets/framework.dart:4486:5)
#65     Element.updateChild (package:flutter/src/widgets/framework.dart:3052:15)
#66     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5525:14)
#67     Element.updateChild (package:flutter/src/widgets/framework.dart:3052:15)
#68     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4316:16)
#69     Element.rebuild (package:flutter/src/widgets/framework.dart:4020:5)
#70     StatelessElement.update (package:flutter/src/widgets/framework.dart:4371:5)
#71     Element.updateChild (package:flutter/src/widgets/framework.dart:3052:15)
#72     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5525:14)
#73     Element.updateChild (package:flutter/src/widgets/framework.dart:3052:15)
#74     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4316:16)
#75     Element.rebuild (package:flutter/src/widgets/framework.dart:4020:5)
#76     StatelessElement.update (package:flutter/src/widgets/framework.dart:4371:5)
#77     Element.updateChild (package:flutter/src/widgets/framework.dart:3052:15)
#78     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5525:14)
#79     Element.updateChild (package:flutter/src/widgets/framework.dart:3052:15)
#80     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4316:16)
#81     Element.rebuild (package:flutter/src/widgets/framework.dart:4020:5)
#82     StatefulElement.update (package:flutter/src/widgets/framework.dart:4486:5)
#83     Element.updateChild (package:flutter/src/widgets/framework.dart:3052:15)
#84     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4316:16)
#85     Element.rebuild (package:flutter/src/widgets/framework.dart:4020:5)
#86     StatefulElement.update (package:flutter/src/widgets/framework.dart:4486:5)
#87     Element.updateChild (package:flutter/src/widgets/framework.dart:3052:15)
#88     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5525:14)
#89     Element.updateChild (package:flutter/src/widgets/framework.dart:3052:15)
#90     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4316:16)
#91     Element.rebuild (package:flutter/src/widgets/framework.dart:4020:5)
#92     StatelessElement.update (package:flutter/src/widgets/framework.dart:4371:5)
#93     Element.updateChild (package:flutter/src/widgets/framework.dart:3052:15)
#94     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5525:14)
#95     Element.updateChild (package:flutter/src/widgets/framework.dart:3052:15)
#96     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4316:16)
#97     Element.rebuild (package:flutter/src/widgets/framework.dart:4020:5)
#98     StatelessElement.update (package:flutter/src/widgets/framework.dart:4371:5)
#99     Element.updateChild (package:flutter/src/widgets/framework.dart:3052:15)
#100    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5525:14)
#101    Element.updateChild (package:flutter/src/widgets/framework.dart:3052:15)
#102    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5525:14)
#103    Element.updateChild (package:flutter/src/widgets/framework.dart:3052:15)
#104    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5525:14)
#105    Element.updateChild (package:flutter/src/widgets/framework.dart:3052:15)
#106    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5525:14)
#107    Element.updateChild (package:flutter/src/widgets/framework.dart:3052:15)
#108    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4316:16)
#109    Element.rebuild (package:flutter/src/widgets/framework.dart:4020:5)
#110    StatelessElement.update (package:flutter/src/widgets/framework.dart:4371:5)
#111    Element.updateChild (package:flutter/src/widgets/framework.dart:3052:15)
#112    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5525:14)
#113    Element.updateChild (package:flutter/src/widgets/framework.dart:3052:15)
#114    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4316:16)
#115    Element.rebuild (package:flutter/src/widgets/framework.dart:4020:5)
#116    StatefulElement.update (package:flutter/src/widgets/framework.dart:4486:5)
#117    Element.updateChild (package:flutter/src/widgets/framework.dart:3052:15)
#118    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5525:14)
#119    Element.updateChild (package:flutter/src/widgets/framework.dart:3052:15)
#120    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4316:16)
#121    Element.rebuild (package:flutter/src/widgets/framework.dart:4020:5)
#122    StatelessElement.update (package:flutter/src/widgets/framework.dart:4371:5)
#123    Element.updateChild (package:flutter/src/widgets/framework.dart:3052:15)
#124    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4316:16)
#125    Element.rebuild (package:flutter/src/widgets/framework.dart:4020:5)
#126    ProxyElement.update (package:flutter/src/widgets/framework.dart:4630:5)
#127    Element.updateChild (package:flutter/src/widgets/framework.dart:3052:15)
#128    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5525:14)
#129    Element.updateChild (package:flutter/src/widgets/framework.dart:3052:15)
#130    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5525:14)
#131    Element.updateChild (package:flutter/src/widgets/framework.dart:3052:15)
#132    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5525:14)
#133    Element.updateChild (package:flutter/src/widgets/framework.dart:3052:15)
#134    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5525:14)
#135    Element.updateChild (package:flutter/src/widgets/framework.dart:3052:15)
#136    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4316:16)
#137    Element.rebuild (package:flutter/src/widgets/framework.dart:4020:5)
#138    StatelessElement.update (package:flutter/src/widgets/framework.dart:4371:5)
#139    Element.updateChild (package:flutter/src/widgets/framework.dart:3052:15)
#140    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4316:16)
#141    Element.rebuild (package:flutter/src/widgets/framework.dart:4020:5)
#142    StatefulElement.update (package:flutter/src/widgets/framework.dart:4486:5)
#143    Element.updateChild (package:flutter/src/widgets/framework.dart:3052:15)
#144    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4316:16)
#145    Element.rebuild (package:flutter/src/widgets/framework.dart:4020:5)
#146    StatefulElement.update (package:flutter/src/widgets/framework.dart:4486:5)
#147    Element.updateChild (package:flutter/src/widgets/framework.dart:3052:15)
#148    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4316:16)
#149    Element.rebuild (package:flutter/src/widgets/framework.dart:4020:5)
#150    ProxyElement.update (package:flutter/src/widgets/framework.dart:4630:5)
#151    Element.updateChild (package:flutter/src/widgets/framework.dart:3052:15)
#152    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4316:16)
#153    Element.rebuild (package:flutter/src/widgets/framework.dart:4020:5)
#154    StatelessElement.update (package:flutter/src/widgets/framework.dart:4371:5)
#155    Element.updateChild (package:flutter/src/widgets/framework.dart:3052:15)
#156    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4316:16)
#157    Element.rebuild (package:flutter/src/widgets/framework.dart:4020:5)
#158    ProxyElement.update (package:flutter/src/widgets/framework.dart:4630:5)
#159    Element.updateChild (package:flutter/src/widgets/framework.dart:3052:15)
#160    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5525:14)
#161    Element.updateChild (package:flutter/src/widgets/framework.dart:3052:15)
#162    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4316:16)
#163    Element.rebuild (package:flutter/src/widgets/framework.dart:4020:5)
#164    StatelessElement.update (package:flutter/src/widgets/framework.dart:4371:5)
#165    Element.updateChild (package:flutter/src/widgets/framework.dart:3052:15)
#166    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5525:14)
#167    Element.updateChild (package:flutter/src/widgets/framework.dart:3052:15)
#168    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5234:32)
#169    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5637:17)
#170    Element.updateChild (package:flutter/src/widgets/framework.dart:3052:15)
#171    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5525:14)
#172    Element.updateChild (package:flutter/src/widgets/framework.dart:3052:15)
#173    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4316:16)
#174    Element.rebuild (package:flutter/src/widgets/framework.dart:4020:5)
#175    StatelessElement.update (package:flutter/src/widgets/framework.dart:4371:5)
#176    Element.updateChild (package:flutter/src/widgets/framework.dart:3052:15)
#177    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4316:16)
#178    Element.rebuild (package:flutter/src/widgets/framework.dart:4020:5)
#179    StatelessElement.update (package:flutter/src/widgets/framework.dart:4371:5)
#180    Element.updateChild (package:flutter/src/widgets/framework.dart:3052:15)
#181    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4316:16)
#182    Element.rebuild (package:flutter/src/widgets/framework.dart:4020:5)
#183    ProxyElement.update (package:flutter/src/widgets/framework.dart:4630:5)
#184    Element.updateChild (package:flutter/src/widgets/framework.dart:3052:15)
#185    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4316:16)
#186    Element.rebuild (package:flutter/src/widgets/framework.dart:4020:5)
#187    ProxyElement.update (package:flutter/src/widgets/framework.dart:4630:5)
#188    Element.updateChild (package:flutter/src/widgets/framework.dart:3052:15)
#189    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5234:32)
#190    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5637:17)
#191    Element.updateChild (package:flutter/src/widgets/framework.dart:3052:15)
#192    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4316:16)
#193    Element.rebuild (package:flutter/src/widgets/framework.dart:4020:5)
#194    StatefulElement.update (package:flutter/src/widgets/framework.dart:4486:5)
#195    Element.updateChild (package:flutter/src/widgets/framework.dart:3052:15)
#196    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4316:16)
#197    Element.rebuild (package:flutter/src/widgets/framework.dart:4020:5)
#198    ProxyElement.update (package:flutter/src/widgets/framework.dart:4630:5)
#199    Element.updateChild (package:flutter/src/widgets/framework.dart:3052:15)
#200    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4316:16)
#201    Element.rebuild (package:flutter/src/widgets/framework.dart:4020:5)
#202    StatefulElement.update (package:flutter/src/widgets/framework.dart:4486:5)
#203    Element.updateChild (package:flutter/src/widgets/framework.dart:3052:15)
#204    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5525:14)
#205    Element.updateChild (package:flutter/src/widgets/framework.dart:3052:15)
#206    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4316:16)
#207    Element.rebuild (package:flutter/src/widgets/framework.dart:4020:5)
#208    StatelessElement.update (package:flutter/src/widgets/framework.dart:4371:5)
#209    Element.updateChild (package:flutter/src/widgets/framework.dart:3052:15)
#210    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5525:14)
#211    Element.updateChild (package:flutter/src/widgets/framework.dart:3052:15)
#212    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4316:16)
#213    Element.rebuild (package:flutter/src/widgets/framework.dart:4020:5)
#214    StatefulElement.update (package:flutter/src/widgets/framework.dart:4486:5)
#215    Element.updateChild (package:flutter/src/widgets/framework.dart:3052:15)
#216    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4316:16)
#217    Element.rebuild (package:flutter/src/widgets/framework.dart:4020:5)
#218    StatefulElement.update (package:flutter/src/widgets/framework.dart:4486:5)
#219    Element.updateChild (package:flutter/src/widgets/framework.dart:3052:15)
#220    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4316:16)
#221    Element.rebuild (package:flutter/src/widgets/framework.dart:4020:5)
#222    ProxyElement.update (package:flutter/src/widgets/framework.dart:4630:5)
#223    Element.updateChild (package:flutter/src/widgets/framework.dart:3052:15)
#224    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4316:16)
#225    Element.rebuild (package:flutter/src/widgets/framework.dart:4020:5)
#226    ProxyElement.update (package:flutter/src/widgets/framework.dart:4630:5)
#227    Element.updateChild (package:flutter/src/widgets/framework.dart:3052:15)
#228    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4316:16)
#229    Element.rebuild (package:flutter/src/widgets/framework.dart:4020:5)
#230    StatefulElement.update (package:flutter/src/widgets/framework.dart:4486:5)
#231    Element.updateChild (package:flutter/src/widgets/framework.dart:3052:15)
#232    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5525:14)
#233    Element.updateChild (package:flutter/src/widgets/framework.dart:3052:15)
#234    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4316:16)
#235    Element.rebuild (package:flutter/src/widgets/framework.dart:4020:5)
#236    StatelessElement.update (package:flutter/src/widgets/framework.dart:4371:5)
#237    Element.updateChild (package:flutter/src/widgets/framework.dart:3052:15)
#238    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5525:14)
#239    Element.updateChild (package:flutter/src/widgets/framework.dart:3052:15)
#240    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4316:16)
#241    Element.rebuild (package:flutter/src/widgets/framework.dart:4020:5)
#242    StatefulElement.update (package:flutter/src/widgets/framework.dart:4486:5)
#243    Element.updateChild (package:flutter/src/widgets/framework.dart:3052:15)
#244    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4316:16)
#245    Element.rebuild (package:flutter/src/widgets/framework.dart:4020:5)
#246    StatelessElement.update (package:flutter/src/widgets/framework.dart:4371:5)
#247    Element.updateChild (package:flutter/src/widgets/framework.dart:3052:15)
#248    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4316:16)
#249    Element.rebuild (package:flutter/src/widgets/framework.dart:4020:5)
#250    StatefulElement.update (package:flutter/src/widgets/framework.dart:4486:5)
#251    Element.updateChild (package:flutter/src/widgets/framework.dart:3052:15)
#252    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4316:16)
#253    Element.rebuild (package:flutter/src/widgets/framework.dart:4020:5)
#254    ProxyElement.update (package:flutter/src/widgets/framework.dart:4630:5)
#255    Element.updateChild (package:flutter/src/widgets/framework.dart:3052:15)
#256    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5525:14)
#257    Element.updateChild (package:flutter/src/widgets/framework.dart:3052:15)
#258    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4316:16)
#259    Element.rebuild (package:flutter/src/widgets/framework.dart:4020:5)
#260    StatelessElement.update (package:flutter/src/widgets/framework.dart:4371:5)
#261    Element.updateChild (package:flutter/src/widgets/framework.dart:3052:15)
#262    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5525:14)
#263    Element.updateChild (package:flutter/src/widgets/framework.dart:3052:15)
#264    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5525:14)
#265    Element.updateChild (package:flutter/src/widgets/framework.dart:3052:15)
#266    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4316:16)
#267    Element.rebuild (package:flutter/src/widgets/framework.dart:4020:5)
#268    StatefulElement.update (package:flutter/src/widgets/framework.dart:4486:5)
#269    Element.updateChild (package:flutter/src/widgets/framework.dart:3052:15)
#270    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5525:14)
#271    Element.updateChild (package:flutter/src/widgets/framework.dart:3052:15)
#272    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5525:14)
#273    Element.updateChild (package:flutter/src/widgets/framework.dart:3052:15)
#274    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4316:16)
#275    Element.rebuild (package:flutter/src/widgets/framework.dart:4020:5)
#276    StatefulElement.update (package:flutter/src/widgets/framework.dart:4486:5)
#277    Element.updateChild (package:flutter/src/widgets/framework.dart:3052:15)
#278    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4316:16)
#279    Element.rebuild (package:flutter/src/widgets/framework.dart:4020:5)
#280    StatelessElement.update (package:flutter/src/widgets/framework.dart:4371:5)
#281    Element.updateChild (package:flutter/src/widgets/framework.dart:3052:15)
#282    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4316:16)
#283    Element.rebuild (package:flutter/src/widgets/framework.dart:4020:5)
#284    StatefulElement.update (package:flutter/src/widgets/framework.dart:4486:5)
#285    Element.updateChild (package:flutter/src/widgets/framework.dart:3052:15)
#286    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5525:14)
#287    Element.updateChild (package:flutter/src/widgets/framework.dart:3052:15)
#288    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4316:16)
#289    Element.rebuild (package:flutter/src/widgets/framework.dart:4020:5)
#290    ProxyElement.update (package:flutter/src/widgets/framework.dart:4630:5)
#291    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:94:11)
#292    Element.updateChild (package:flutter/src/widgets/framework.dart:3052:15)
#293    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5525:14)
#294    Element.updateChild (package:flutter/src/widgets/framework.dart:3052:15)
#295    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4316:16)
#296    Element.rebuild (package:flutter/src/widgets/framework.dart:4020:5)
#297    StatefulElement.update (package:flutter/src/widgets/framework.dart:4486:5)
#298    Element.updateChild (package:flutter/src/widgets/framework.dart:3052:15)
#299    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4316:16)
#300    Element.rebuild (package:flutter/src/widgets/framework.dart:4020:5)
#301    StatelessElement.update (package:flutter/src/widgets/framework.dart:4371:5)
#302    Element.updateChild (package:flutter/src/widgets/framework.dart:3052:15)
#303    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5525:14)
#304    Element.updateChild (package:flutter/src/widgets/framework.dart:3052:15)
#305    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4316:16)
#306    Element.rebuild (package:flutter/src/widgets/framework.dart:4020:5)
#307    ProxyElement.update (package:flutter/src/widgets/framework.dart:4630:5)
#308    Element.updateChild (package:flutter/src/widgets/framework.dart:3052:15)
#309    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4316:16)
#310    Element.rebuild (package:flutter/src/widgets/framework.dart:4020:5)
#311    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2507:33)
#312    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:796:20)
#313    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:283:5)
#314    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1108:15)
#315    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1047:9)
#316    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:963:5)
#317    _rootRun (dart:async/zone.dart:1126:13)
#318    _CustomZone.run (dart:async/zone.dart:1023:19)
#319    _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#320    _invoke (dart:ui/hooks.dart:259:10)
#321    _drawFrame (dart:ui/hooks.dart:217:3)

**Comment by CarGuo** [comment]
https://github.com/CarGuo/gsy_github_app_flutter/issues/650
