### ISSUE TITLE
Android 登录出现异常

### ISSUE THREAD

**Issue by Hackerofshi** [CarGuo/gsy_github_app_flutter#654]
I/flutter ( 6039): type 'String' is not a subtype of type 'Map<String, dynamic>'
I/flutter ( 6039): 请求异常: DioError [DioErrorType.DEFAULT]: SocketException: OS Error: Connection refused, errno = 111, address = api.github.com, port = 47568

**Comment by CarGuo** [comment]
Connection refused 参考 https://github.com/CarGuo/gsy_github_app_flutter/issues/643
