### ISSUE TITLE
关于json序列化的问题

### ISSUE THREAD

**Issue by shexm** [CarGuo/gsy_github_app_flutter#666]
大佬，刚刚学flutter，很幸运看到了你的教程和项目，我看到model文件夹里面的dart创建model类的文件，有些类的构造函数是带参数的，比如  
`
  IssueEvent(
    this.id,
    this.user,
    this.createdAt,
    this.updatedAt,
    this.authorAssociation,
    this.body,
    this.bodyHtml,
    this.type,
    this.htmlUrl,
  );
`有些却没有，比如`
EventPayload();
`，这里我很疑惑，什么时候需要参数什么时候不需要，另外className.fromJson(json)不就是我们序列化使用的命名构造函数吗？className()这个构造函数还需要吗？

**Comment by CarGuo** [comment]
`IssueEvent `和 `EventPayload` 在默认构造函数上需要不需要 `this` 都可以，因为成员都没有加上 `final`，如果加上final 的就一定要有 `this.xxx` 做出生后。


`className.fromJson` 也是构造方法而不是普通方法，定义这个模板之后  `_$IssueEventFromJson` 等对应 `IssueEvent.g.dart` 文件都是靠命令后直接生成的。

**Comment by shexm** [comment]
我感到困惑的是构造函数的参数，IssueEvent有带参数，EventPayload没有带参数，另外className.fromJson也是构造方法，那可不可以干脆不写默认构造函数，还有就是一些方法比如common_utils.dart中
```
  static saveImage(String url) async {
      Future<String> _findPath(String imageUrl) async {
        final file = await DefaultCacheManager().getSingleFile(url);
        if (file == null) {
          return null;
        }
        Directory localPath = await CommonUtils.getLocalPath();
        if (localPath == null) {
          return null;
        }
        final name = splitFileNameByPath(file.path);
        final result = await file.copy(localPath.path + name);
        return result.path;
      }
      return _findPath(url);
  }
```
这个方法为什么不是像`static Future<String> getDeviceInfo() async`写成`static Future saveImage(String url) async `而不用写返回值类型
