### ISSUE TITLE
项目启动不起来

### ISSUE THREAD

**Issue by T-toghter** [CarGuo/gsy_github_app_flutter#667]
flutter run失败，项目启动不了
![1586399095160](https://user-images.githubusercontent.com/35291465/78851458-6cd19880-7a4c-11ea-880b-54efeed53ad6.jpg)

**Comment by CarGuo** [comment]
你这个log看不全也看不出问题

**Comment by T-toghter** [comment]
这是完整的报错（已经‘梯子’后再flutter packages get），本人mac


Launching lib/main.dart on iPhone 8 in debug mode...
Running pod install...
  125.7s (!)
CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

    Finding Podfile changes
      - Flutter
      - android_intent
      - connectivity
      - device_info
      - flutter_webview_plugin
      - fluttertoast
      - package_info
      - path_provider
      - permission_handler
      - share
      - shared_preferences
      - shared_preferences_macos
      - shared_preferences_web
      - sqflite
      - url_launcher
      - url_launcher_macos
      - url_launcher_web
      - webview_flutter

    Fetching external sources
    -> Fetching podspec for `Flutter` from `Flutter`
    -> Fetching podspec for `android_intent` from
    `.symlinks/plugins/android_intent/ios`
    -> Fetching podspec for `connectivity` from
    `.symlinks/plugins/connectivity/ios`
    -> Fetching podspec for `device_info` from
    `.symlinks/plugins/device_info/ios`
    -> Fetching podspec for `flutter_webview_plugin` from
    `.symlinks/plugins/flutter_webview_plugin/ios`
    -> Fetching podspec for `fluttertoast` from
    `.symlinks/plugins/fluttertoast/ios`
    -> Fetching podspec for `package_info` from
    `.symlinks/plugins/package_info/ios`
    -> Fetching podspec for `path_provider` from
    `.symlinks/plugins/path_provider/ios`
    -> Fetching podspec for `permission_handler` from
    `.symlinks/plugins/permission_handler/ios`
    -> Fetching podspec for `share` from `.symlinks/plugins/share/ios`
    -> Fetching podspec for `shared_preferences` from
    `.symlinks/plugins/shared_preferences/ios`
    -> Fetching podspec for `shared_preferences_macos` from
    `.symlinks/plugins/shared_preferences_macos/ios`
    -> Fetching podspec for `shared_preferences_web` from
    `.symlinks/plugins/shared_preferences_web/ios`
    -> Fetching podspec for `sqflite` from `.symlinks/plugins/sqflite/ios`
    -> Fetching podspec for `url_launcher` from
    `.symlinks/plugins/url_launcher/ios`
    -> Fetching podspec for `url_launcher_macos` from
    `.symlinks/plugins/url_launcher_macos/ios`
    -> Fetching podspec for `url_launcher_web` from
    `.symlinks/plugins/url_launcher_web/ios`
    -> Fetching podspec for `webview_flutter` from
    `.symlinks/plugins/webview_flutter/ios`

    Resolving dependencies of `Podfile`
      CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local
      because checking is only perfomed in repo update
      CDN: trunk Relative path: all_pods_versions_c_7_9.txt exists! Returning
      local because checking is only perfomed in repo update
      CDN: trunk Relative path:
      Specs/c/7/9/Reachability/3.2/Reachability.podspec.json exists! Returning
      local because checking is only perfomed in repo update
      CDN: trunk Relative path: all_pods_versions_f_4_e.txt exists! Returning
      local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/f/4/e/FMDB/2.7.5/FMDB.podspec.json exists!
      Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path:
      Specs/c/7/9/Reachability/3.2/Reachability.podspec.json exists! Returning
      local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/f/4/e/FMDB/2.7.2/FMDB.podspec.json exists!
      Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/f/4/e/FMDB/2.7.2/FMDB.podspec.json exists!
      Returning local because checking is only perfomed in repo update

    Comparing resolved specification to the sandbox manifest
      A FMDB
      A Flutter
      A Reachability
      A android_intent
      A connectivity
      A device_info
      A flutter_webview_plugin
      A fluttertoast
      A package_info
      A path_provider
      A permission_handler
      A share
      A shared_preferences
      A shared_preferences_macos
      A shared_preferences_web
      A sqflite
      A url_launcher
      A url_launcher_macos
      A url_launcher_web
      A webview_flutter

    Downloading dependencies

    -> Installing FMDB (2.7.2)
     > Git download
     > Git download
         $ /usr/bin/git clone https://github.com/ccgus/fmdb.git
         /var/folders/27/wclcy9wn37j1pvd5s0f2sjm00000gp/T/d20200409-6288-m25sr2
         --template= --single-branch --depth 1 --branch 2.7.2
      > Copying FMDB from
      `/Users/xucongmac/Library/Caches/CocoaPods/Pods/Release/FMDB/2.7.2-6198a`
      to `Pods/FMDB`

    -> Installing Flutter (1.0.0)

    -> Installing Reachability (3.2)
     > Git download
     > Git download
         $ /usr/bin/git clone https://github.com/tonymillion/Reachability.git
         /var/folders/27/wclcy9wn37j1pvd5s0f2sjm00000gp/T/d20200409-6288-13h24pg
         --template= --single-branch --depth 1 --branch v3.2

    [!] Error installing Reachability
    [!] /usr/bin/git clone https://github.com/tonymillion/Reachability.git
    /var/folders/27/wclcy9wn37j1pvd5s0f2sjm00000gp/T/d20200409-6288-13h24pg
    --template= --single-branch --depth 1 --branch v3.2

    Cloning into
    '/var/folders/27/wclcy9wn37j1pvd5s0f2sjm00000gp/T/d20200409-6288-13h24pg'...
    fatal: unable to access 'https://github.com/tonymillion/Reachability.git/':
    LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to github.com:443

    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/downloader.rb:14
    2:in `rescue in execute_command'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/downloader.rb:13
    9:in `execute_command'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-downloader-1.3.0/lib/cocoapods-downl
    oader/base.rb:154:in `block in executable'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-downloader-1.3.0/lib/cocoapods-downl
    oader/git.rb:79:in `block in clone'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/downloader.rb:17
    3:in `block in ui_sub_action'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/user_interface.r
    b:64:in `section'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/downloader.rb:17
    2:in `ui_sub_action'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-downloader-1.3.0/lib/cocoapods-downl
    oader/git.rb:77:in `clone'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-downloader-1.3.0/lib/cocoapods-downl
    oader/git.rb:45:in `download!'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-downloader-1.3.0/lib/cocoapods-downl
    oader/base.rb:82:in `block in download'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/downloader.rb:15
    7:in `block in ui_action'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/user_interface.r
    b:64:in `section'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/downloader.rb:15
    6:in `ui_action'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-downloader-1.3.0/lib/cocoapods-downl
    oader/base.rb:80:in `download'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/downloader.rb:10
    8:in `download_source'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/downloader.rb:75
    :in `download_request'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/downloader/cache
    .rb:171:in `download'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/downloader/cache
    .rb:154:in `block in uncached_pod'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/downloader/cache
    .rb:181:in `in_tmpdir'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/downloader/cache
    .rb:153:in `uncached_pod'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/downloader/cache
    .rb:33:in `download_pod'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/downloader.rb:42
    :in `download'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/pod_so
    urce_installer.rb:117:in `download_source'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/pod_so
    urce_installer.rb:69:in `install!'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:557
    :in `install_source_of_pod'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:508
    :in `block (2 levels) in install_pod_sources'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/user_interface.r
    b:86:in `titled_section'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:507
    :in `block in install_pod_sources'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:490
    :in `each'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:490
    :in `install_pod_sources'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:249
    :in `block in download_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/user_interface.r
    b:64:in `section'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:248
    :in `download_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:157
    :in `install!'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/command/install.
    rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in
    `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/command.rb:52:in
    `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/bin/pod:55:in `<top
    (required)>'
    /usr/local/bin/pod:23:in `load'
    /usr/local/bin/pod:23:in `<main>'

Error output from CocoaPods:
↳
    /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/un
    iversal-darwin19/rbconfig.rb:229: warning: Insecure world writable dir
    /Users/xucongmac/flutter/flutter/bin in PATH, mode 040777
         Cloning into
         '/var/folders/27/wclcy9wn37j1pvd5s0f2sjm00000gp/T/d20200409-6288-m25sr2
         '...
         Note: checking out 'd1fc235264cc0f84924115e844ea4dd1ba391c7b'.

         You are in 'detached HEAD' state. You can look around, make
         experimental
         changes and commit them, and you can discard any commits you make in
         this
         state without impacting any branches by performing another checkout.

         If you want to create a new branch to retain commits you create, you
         may
         do so (now or later) by using -b with the checkout command again.
         Example:

           git checkout -b <new-branch-name>

         Cloning into
         '/var/folders/27/wclcy9wn37j1pvd5s0f2sjm00000gp/T/d20200409-6288-13h24p
         g'...
         fatal: unable to access
         'https://github.com/tonymillion/Reachability.git/': LibreSSL
         SSL_connect: SSL_ERROR_SYSCALL in connection to github.com:443

    [!] Automatically assigning platform `iOS` with version `8.0` on target
    `Runner` because no platform was specified. Please specify a platform for
    this target in your Podfile. See
    `https://guides.cocoapods.org/syntax/podfile.html#platform`.

Error running pod install
Error launching application on iPhone 8.

**Comment by T-toghter** [comment]
> 你这个log看不全也看不出问题

完整的我已经发出来了

**Comment by CarGuo** [comment]
[!] Error installing Reachability
[!] /usr/bin/git clone https://github.com/tonymillion/Reachability.git

**Comment by T-toghter** [comment]
这是啥意思啊？

**Comment by CarGuo** [comment]
pod 安装下载库的的时候失败了，这个很多因素影响，你可以把你本地的 CocoaPods 换成 1.7 左右的版本，我现在用的才是 1.6.1

**Comment by T-toghter** [comment]
我降到了1.7的版本，还是报错；按照报错的提示执行了pod repo update，但flutter run还是继续报错


Launching lib/main.dart on iPhone 8 in debug mode...
Running pod install...                                              1.0s
CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

    Finding Podfile changes
      - Flutter
      - android_intent
      - connectivity
      - device_info
      - flutter_webview_plugin
      - fluttertoast
      - package_info
      - path_provider
      - permission_handler
      - share
      - shared_preferences
      - shared_preferences_macos
      - shared_preferences_web
      - sqflite
      - url_launcher
      - url_launcher_macos
      - url_launcher_web
      - webview_flutter

    Fetching external sources
    -> Fetching podspec for `Flutter` from `Flutter`
    -> Fetching podspec for `android_intent` from
    `.symlinks/plugins/android_intent/ios`
    -> Fetching podspec for `connectivity` from
    `.symlinks/plugins/connectivity/ios`
    -> Fetching podspec for `device_info` from
    `.symlinks/plugins/device_info/ios`
    -> Fetching podspec for `flutter_webview_plugin` from
    `.symlinks/plugins/flutter_webview_plugin/ios`
    -> Fetching podspec for `fluttertoast` from
    `.symlinks/plugins/fluttertoast/ios`
    -> Fetching podspec for `package_info` from
    `.symlinks/plugins/package_info/ios`
    -> Fetching podspec for `path_provider` from
    `.symlinks/plugins/path_provider/ios`
    -> Fetching podspec for `permission_handler` from
    `.symlinks/plugins/permission_handler/ios`
    -> Fetching podspec for `share` from `.symlinks/plugins/share/ios`
    -> Fetching podspec for `shared_preferences` from
    `.symlinks/plugins/shared_preferences/ios`
    -> Fetching podspec for `shared_preferences_macos` from
    `.symlinks/plugins/shared_preferences_macos/ios`
    -> Fetching podspec for `shared_preferences_web` from
    `.symlinks/plugins/shared_preferences_web/ios`
    -> Fetching podspec for `sqflite` from `.symlinks/plugins/sqflite/ios`
    -> Fetching podspec for `url_launcher` from
    `.symlinks/plugins/url_launcher/ios`
    -> Fetching podspec for `url_launcher_macos` from
    `.symlinks/plugins/url_launcher_macos/ios`
    -> Fetching podspec for `url_launcher_web` from
    `.symlinks/plugins/url_launcher_web/ios`
    -> Fetching podspec for `webview_flutter` from
    `.symlinks/plugins/webview_flutter/ios`

    Resolving dependencies of `Podfile`
      CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local
      because checking is only perfomed in repo update
    [!] Unable to find a specification for `Reachability` depended upon by
    `connectivity`

    You have either:
     * out-of-date source repos which you can update with `pod repo update` or
     with `pod install --repo-update`.
     * mistyped the name or version.
     * not added the source repo that hosts the Podspec to your Podfile.

    Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod
    install` by default.

    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.0/lib/cocoapods/resolver.rb:362:
    in `find_cached_set'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.0/lib/cocoapods/resolver.rb:332:
    in `specifications_for_dependency'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.0/lib/cocoapods/resolver.rb:139:
    in `search_for'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.0/lib/cocoapods/resolver.rb:248:
    in `block in sort_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.0/lib/cocoapods/resolver.rb:241:
    in `each'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.0/lib/cocoapods/resolver.rb:241:
    in `sort_by'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.0/lib/cocoapods/resolver.rb:241:
    in `sort_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specif
    ication_provider.rb:53:in `block in sort_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specif
    ication_provider.rb:70:in `with_no_such_dependency_error_handling'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specif
    ication_provider.rb:52:in `sort_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:75
    4:in `push_state_for_requirements'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:74
    6:in `require_nested_dependencies_for'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:72
    9:in `activate_new_spec'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:68
    6:in `attempt_to_activate'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:25
    4:in `process_topmost_state'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:18
    2:in `resolve'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolver.rb:43:i
    n `resolve'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.0/lib/cocoapods/resolver.rb:88:i
    n `resolve'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.0/lib/cocoapods/installer/analyz
    er.rb:939:in `block in resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.0/lib/cocoapods/user_interface.r
    b:64:in `section'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.0/lib/cocoapods/installer/analyz
    er.rb:937:in `resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.0/lib/cocoapods/installer/analyz
    er.rb:118:in `analyze'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.0/lib/cocoapods/installer.rb:398
    :in `analyze'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.0/lib/cocoapods/installer.rb:221
    :in `block in resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.0/lib/cocoapods/user_interface.r
    b:64:in `section'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.0/lib/cocoapods/installer.rb:220
    :in `resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.0/lib/cocoapods/installer.rb:156
    :in `install!'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.0/lib/cocoapods/command/install.
    rb:51:in `run'
    /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in
    `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.0/lib/cocoapods/command.rb:52:in
    `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.0/bin/pod:55:in `<top
    (required)>'
    /usr/local/bin/pod:23:in `load'
    /usr/local/bin/pod:23:in `<main>'

Error output from CocoaPods:
↳
    /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/un
    iversal-darwin19/rbconfig.rb:229: warning: Insecure world writable dir
    /Users/xucongmac/flutter/flutter/bin in PATH, mode 040777

    [!] Automatically assigning platform `ios` with version `8.0` on target
    `Runner` because no platform was specified. Please specify a platform for
    this target in your Podfile. See
    `https://guides.cocoapods.org/syntax/podfile.html#platform`.

Error: CocoaPods's specs repository is too out-of-date to satisfy dependencies.
To update the CocoaPods specs, run:
  pod repo update



Error running pod install
Error launching application on iPhone 8.

**Comment by T-toghter** [comment]
最后解决了，知道了这么解决的了。只要在ios文件下执行下pod update就可以了。反正就是胡乱搞了一天，终于可以启动项目了
