### ISSUE TITLE
登陆不了

### ISSUE THREAD

**Issue by T-toghter** [CarGuo/gsy_github_app_flutter#668]
输入github的账号和密码后，报422

**Comment by T-toghter** [comment]
![1586420871520](https://user-images.githubusercontent.com/35291465/78874509-1598eb80-7a7f-11ea-8fa7-0f5770f90b1b.jpg)

**Comment by T-toghter** [comment]
![1586423785882](https://user-images.githubusercontent.com/35291465/78879000-e20d8f80-7a85-11ea-97bf-194b807828b8.jpg)
这个申请的账号和密码都没有用啊，为什么一定要用这个登陆啊，这不是故意恶心人嘛？怎么想的

**Comment by T-toghter** [comment]
![1586423785882](https://user-images.githubusercontent.com/35291465/78879295-4b8d9e00-7a86-11ea-8e7f-d667efaada9c.jpg)

**Comment by CarGuo** [comment]
1、这个 id 和 sercet 是配置在 NetConfig 里的
2、登录推荐用授权方式登录，账号密码登录的话用用户名和密码，不要用邮箱。
3、登录是因为 Github Api 需要 token 。
4、有时候 Github 的 Api 会因为 DNS 或者 GW 等原因抽风，如果出现为题可以换一个网络环境

**Comment by T-toghter** [comment]
所有的都弄了啊，还是不行啊，账号密码登陆上不了，安全登陆进去是百度啊，和你的app没有半毛钱关系
![1586481685354](https://user-images.githubusercontent.com/35291465/78953875-d913d100-7b0c-11ea-8a57-6793a1762d4a.jpg)
![1586481651897](https://user-images.githubusercontent.com/35291465/78953882-df09b200-7b0c-11ea-9e0e-908af1c5c430.jpg)
![1586481707107](https://user-images.githubusercontent.com/35291465/78953894-e3ce6600-7b0c-11ea-8b9d-d10cc3327098.jpg)

**Comment by T-toghter** [comment]
所有的登陆方式都试了，还是不行，你这个是个假的吧，一个登陆搞的那么恶心不让人进去的
![1586482380355](https://user-images.githubusercontent.com/35291465/78954329-63a90000-7b0e-11ea-9eb4-97c03c1e055d.jpg)

**Comment by CarGuo** [comment]
怎么可能····你看其他 issue ，而且安全登录的地址是如下，怎么可能是百度····
```
  static getOAuthUrl() {
    return "https://github.com/login/oauth/authorize?client_id"
        "=${NetConfig.CLIENT_ID}&state=app&"
        "redirect_uri=gsygithubapp://authed";
  }
```

**Comment by T-toghter** [comment]
我截图给你了啊，进来的就是百度啊

**Comment by T-toghter** [comment]
而且更奇怪的是，我什么都没有输入，点击安全登陆就进来百度了
![1586483469857](https://user-images.githubusercontent.com/35291465/78955152-eaf77300-7b10-11ea-8729-e16d25af46cc.jpg)
![1586483486889](https://user-images.githubusercontent.com/35291465/78955158-f0ed5400-7b10-11ea-91ff-e5a139cde94b.jpg)

**Comment by CarGuo** [comment]
大哥，我不知道你代码的 baidu 怎么来的，我现在这边全局搜索并没有 baidu 的链接，而登录不进去有时候也不是我的问题。你可以看看 ： https://www.zhihu.com/question/380450348/answer/1087480860


![image](https://user-images.githubusercontent.com/10770362/78955375-b0daa100-7b11-11ea-98a6-9c533e83f265.png)


因为 github api 自己的问题，官方 app 自己都会出现 api 异常，一般换个网络环境就可以。

**Comment by CarGuo** [comment]
一般你看 log ，是 ：`Connection refused` 的就是 Github API GG 了，你可以试试官方的 app，一样的情况。

```
请求异常: DioError [DioErrorType.DEFAULT]: SocketException: OS Error: Connection refused, errno = 111, address = api.github.com, port = 49557
I/Toast   (16505): Show toast from OpPackageName:com.shuyu.gsygithub.gsygithubappflutter, PackageName:com.shuyu.gsygithub.gsygithubappflutter
```

**Comment by T-toghter** [comment]
我申请的github账户，里面有Authorization callback URL这个要填的，你文档里有说随便填的啊，我填的事百度，所以我点安全登陆就直接去百度的啊，是你说随便填的，我当然随便填啊，我不随便填我也不知道填什么啊，填了什么安全登陆就到哪啊，那还是和你的app没有关系啊

**Comment by CarGuo** [comment]
明白了，这个确实我是忘记改 readme 了，那里应该是 ： gsygithubapp://authed 这个地址。
至于登录不对的你可以按日志输出，如果是  Connection refused 的真的就是 Github Api 的问题，一般遇上这个问题我就换个 wifi 或者 4G ，或者过一会再试就好了

**Comment by CarGuo** [comment]
我刚刚更新了一些代码，如果是遇上 Connection refused  会有特别提示～～
