### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by Andy957** [CarGuo/gsy_github_app_flutter#670]
Unsupported operation: Cannot extract a file path from a URI with a query component
 #0      _Uri.toFilePath (dart:core/uri.dart:2730:7)
#1      new File.fromUri (dart:io/file.dart:267:49)
#2      kDefaultImageBuilder.<anonymous closure> (package:flutter_markdown/src/_functions_io.dart:33:30)
#3      MarkdownBuilder._buildImage (package:flutter_markdown/src/builder.dart:364:35)
#4      MarkdownBuilder.visitElementAfter (package:flutter_markdown/src/builder.dart:306:30)
#5      Element.accept (package:markdown/src/ast.dart:51:15)
#6      Element.accept (package:markdown/src/ast.dart:48:17)
#7      MarkdownBuilder.build (package:flutter_markdown/src/builder.dart:150:12)
#8      _MarkdownWidgetState._parseMarkdown (package:flutter_markdown/src/widget.dart:175:25)
#9      _MarkdownWidgetState.didChangeDependencies (package:flutter_markdown/src/widget.dart:136:5)
#10     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4376:12)
#11     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
#12     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#13     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#14     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
#15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#16     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#17     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
#18     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#19     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#20     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
#21     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#22     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#23     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
#24     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#25     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#26     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#27     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#28     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
#29     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
#30     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#31     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#32     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
#33     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#34     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#35     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#36     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#37     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
#38     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4381:11)
#39     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
#40     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#41     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#42     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
#43     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#44     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#45     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#46     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#47     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
#48     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
#49     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#50     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#51     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#52     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#53     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
#54     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
#55     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#56     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#57     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
#58     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#59     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#60     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
#61     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#62     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#63     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
#64     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#65     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#66     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
#67     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#68     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#69     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#70     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#71     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
#72     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
#73     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#74     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#75     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#76     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#77     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
#78     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4381:11)
#79     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
#80     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#81     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#82     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#83     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#84     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
#85     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4381:11)
#86     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
#87     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#88     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#89     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#90     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#91     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
#92     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
#93     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#94     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#95     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#96     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#97     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
#98     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
#99     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#100    Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#101    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
#102    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#103    Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#104    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
#105    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#106    Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#107    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#108    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#109    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
#110    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
#111    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#112    Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#113    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#114    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#115    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
#116    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
#117    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#118    Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#119    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#120    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#121    StatelessElement.update (package:flutter/src/widgets/framework.dart:4298:5)
#122    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
#123    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#124    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#125    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2432:33)
#126    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:773:20)
#127    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:283:5)
#128    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1102:15)
#129    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1041:9)
#130    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:957:5)
#131    _rootRun (dart:async/zone.dart:1126:13)
#132    _CustomZone.run (dart:async/zone.dart:1023:19)
#133    _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#134    _invoke (dart:ui/hooks.dart:259:10)
#135    _drawFrame (dart:ui/hooks.dart:217:3)

**Comment by CarGuo** [comment]
markdown 解析库问题～
