### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by ngu2008** [CarGuo/gsy_github_app_flutter#671]
Unsupported operation: Cannot extract a file path from a URI with a query component
 #0      _Uri.toFilePath (dart:core/uri.dart:2730)
#1      new File.fromUri (dart:io/file.dart:267)
#2      kDefaultImageBuilder.<anonymous closure> (package:flutter_markdown/src/_functions_io.dart:33)
#3      MarkdownBuilder._buildImage (package:flutter_markdown/src/builder.dart:364)
#4      MarkdownBuilder.visitElementAfter (package:flutter_markdown/src/builder.dart:306)
#5      Element.accept (package:markdown/src/ast.dart:51)
#6      Element.accept (package:markdown/src/ast.dart:48)
#7      MarkdownBuilder.build (package:flutter_markdown/src/builder.dart:150)
#8      _MarkdownWidgetState._parseMarkdown (package:flutter_markdown/src/widget.dart:175)
#9      _MarkdownWidgetState.didChangeDependencies (package:flutter_markdown/src/widget.dart:136)
#10     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4376)
#11     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201)
#12     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194)
#13     Element.updateChild (package:flutter/src/widgets/framework.dart:2988)
#14     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445)
#15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194)
#16     Element.updateChild (package:flutter/src/widgets/framework.dart:2988)
#17     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445)
#18     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194)
#19     Element.updateChild (package:flutter/src/widgets/framework.dart:2988)
#20     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445)
#21     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194)
#22     Element.updateChild (package:flutter/src/widgets/framework.dart:2988)
#23     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445)
#24     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194)
#25     Element.updateChild (package:flutter/src/widgets/framework.dart:2988)
#26     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243)
#27     Element.rebuild (package:flutter/src/widgets/framework.dart:3947)
#28     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206)
#29     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201)
#30     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194)
#31     Element.updateChild (package:flutter/src/widgets/framework.dart:2988)
#32     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445)
#33     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194)
#34     Element.updateChild (package:flutter/src/widgets/framework.dart:2988)
#35     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243)
#36     Element.rebuild (package:flutter/src/widgets/framework.dart:3947)
#37     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206)
#38     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4381)
#39     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201)
#40     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194)
#41     Element.updateChild (package:flutter/src/widgets/framework.dart:2988)
#42     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445)
#43     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194)
#44     Element.updateChild (package:flutter/src/widgets/framework.dart:2988)
#45     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243)
#46     Element.rebuild (package:flutter/src/widgets/framework.dart:3947)
#47     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206)
#48     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201)
#49     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194)
#50     Element.updateChild (package:flutter/src/widgets/framework.dart:2988)
#51     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243)
#52     Element.rebuild (package:flutter/src/widgets/framework.dart:3947)
#53     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206)
#54     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201)
#55     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194)
#56     Element.updateChild (package:flutter/src/widgets/framework.dart:2988)
#57     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445)
#58     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194)
#59     Element.updateChild (package:flutter/src/widgets/framework.dart:2988)
#60     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445)
#61     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194)
#62     Element.updateChild (package:flutter/src/widgets/framework.dart:2988)
#63     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445)
#64     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194)
#65     Element.updateChild (package:flutter/src/widgets/framework.dart:2988)
#66     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445)
#67     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194)
#68     Element.updateChild (package:flutter/src/widgets/framework.dart:2988)
#69     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243)
#70     Element.rebuild (package:flutter/src/widgets/framework.dart:3947)
#71     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206)
#72     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201)
#73     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194)
#74     Element.updateChild (package:flutter/src/widgets/framework.dart:2988)
#75     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243)
#76     Element.rebuild (package:flutter/src/widgets/framework.dart:3947)
#77     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206)
#78     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4381)
#79     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201)
#80     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194)
#81     Element.updateChild (package:flutter/src/widgets/framework.dart:2988)
#82     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243)
#83     Element.rebuild (package:flutter/src/widgets/framework.dart:3947)
#84     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206)
#85     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4381)
#86     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201)
#87     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194)
#88     Element.updateChild (package:flutter/src/widgets/framework.dart:2988)
#89     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243)
#90     Element.rebuild (package:flutter/src/widgets/framework.dart:3947)
#91     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206)
#92     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201)
#93     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194)
#94     Element.updateChild (package:flutter/src/widgets/framework.dart:2988)
#95     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243)
#96     Element.rebuild (package:flutter/src/widgets/framework.dart:3947)
#97     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206)
#98     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201)
#99     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194)
#100    Element.updateChild (package:flutter/src/widgets/framework.dart:2988)
#101    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445)
#102    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194)
#103    Element.updateChild (package:flutter/src/widgets/framework.dart:2988)
#104    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445)
#105    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194)
#106    Element.updateChild (package:flutter/src/widgets/framework.dart:2988)
#107    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243)
#108    Element.rebuild (package:flutter/src/widgets/framework.dart:3947)
#109    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206)
#110    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201)
#111    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194)
#112    Element.updateChild (package:flutter/src/widgets/framework.dart:2988)
#113    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243)
#114    Element.rebuild (package:flutter/src/widgets/framework.dart:3947)
#115    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206)
#116    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201)
#117    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194)
#118    Element.updateChild (package:flutter/src/widgets/framework.dart:2988)
#119    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243)
#120    Element.rebuild (package:flutter/src/widgets/framework.dart:3947)
#121    StatelessElement.update (package:flutter/src/widgets/framework.dart:4298)
#122    Element.updateChild (package:flutter/src/widgets/framework.dart:2977)
#123    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243)
#124    Element.rebuild (package:flutter/src/widgets/framework.dart:3947)
#125    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2432)
#126    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:773)
#127    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:283)
#128    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1102)
#129    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1041)
#130    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:957)
#131    _rootRun (dart:async/zone.dart:1126)
#132    _CustomZone.run (dart:async/zone.dart:1023)
#133    _CustomZone.runGuarded (dart:async/zone.dart:925)
#134    _invoke (dart:ui/hooks.dart:259)
#135    _drawFrame (dart:ui/hooks.dart:217)

**Comment by CarGuo** [comment]
https://github.com/CarGuo/gsy_github_app_flutter/issues/671
