### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by hzg1105** [CarGuo/gsy_github_app_flutter#677]
Unsupported operation: Cannot extract a file path from a URI with a query component
 #0      _SimpleUri.toFilePath (dart:core/uri.dart:4711)
#1      new File.fromUri (dart:io/file.dart:267)
#2      kDefaultImageBuilder.<anonymous closure> (package:flutter_markdown/src/_functions_io.dart:33)
#3      MarkdownBuilder._buildImage (package:flutter_markdown/src/builder.dart:364)
#4      MarkdownBuilder.visitElementAfter (package:flutter_markdown/src/builder.dart:306)
#5      Element.accept (package:markdown/src/ast.dart:51)
#6      Element.accept (package:markdown/src/ast.dart:48)
#7      Element.accept (package:markdown/src/ast.dart:48)
#8      MarkdownBuilder.build (package:flutter_markdown/src/builder.dart:150)
#9      _MarkdownWidgetState._parseMarkdown (package:flutter_markdown/src/widget.dart:175)
#10     _MarkdownWidgetState.didChangeDependencies (package:flutter_markdown/src/widget.dart:136)
#11     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4376)
#12     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201)
#13     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194)
#14     Element.updateChild (package:flutter/src/widgets/framework.dart:2988)
#15     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445)
#16     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194)
#17     Element.updateChild (package:flutter/src/widgets/framework.dart:2988)
#18     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445)
#19     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194)
#20     Element.updateChild (package:flutter/src/widgets/framework.dart:2988)
#21     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445)
#22     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194)
#23     Element.updateChild (package:flutter/src/widgets/framework.dart:2988)
#24     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445)
#25     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194)
#26     Element.updateChild (package:flutter/src/widgets/framework.dart:2988)
#27     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243)
#28     Element.rebuild (package:flutter/src/widgets/framework.dart:3947)
#29     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206)
#30     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201)
#31     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194)
#32     Element.updateChild (package:flutter/src/widgets/framework.dart:2988)
#33     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445)
#34     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194)
#35     Element.updateChild (package:flutter/src/widgets/framework.dart:2988)
#36     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243)
#37     Element.rebuild (package:flutter/src/widgets/framework.dart:3947)
#38     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206)
#39     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4381)
#40     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201)
#41     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194)
#42     Element.updateChild (package:flutter/src/widgets/framework.dart:2988)
#43     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445)
#44     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194)
#45     Element.updateChild (package:flutter/src/widgets/framework.dart:2988)
#46     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243)
#47     Element.rebuild (package:flutter/src/widgets/framework.dart:3947)
#48     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206)
#49     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201)
#50     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194)
#51     Element.updateChild (package:flutter/src/widgets/framework.dart:2988)
#52     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243)
#53     Element.rebuild (package:flutter/src/widgets/framework.dart:3947)
#54     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206)
#55     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201)
#56     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194)
#57     Element.updateChild (package:flutter/src/widgets/framework.dart:2988)
#58     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445)
#59     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194)
#60     Element.updateChild (package:flutter/src/widgets/framework.dart:2988)
#61     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445)
#62     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194)
#63     Element.updateChild (package:flutter/src/widgets/framework.dart:2988)
#64     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445)
#65     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194)
#66     Element.updateChild (package:flutter/src/widgets/framework.dart:2988)
#67     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445)
#68     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194)
#69     Element.updateChild (package:flutter/src/widgets/framework.dart:2988)
#70     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243)
#71     Element.rebuild (package:flutter/src/widgets/framework.dart:3947)
#72     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206)
#73     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201)
#74     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194)
#75     Element.updateChild (package:flutter/src/widgets/framework.dart:2988)
#76     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243)
#77     Element.rebuild (package:flutter/src/widgets/framework.dart:3947)
#78     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206)
#79     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4381)
#80     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201)
#81     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194)
#82     Element.updateChild (package:flutter/src/widgets/framework.dart:2988)
#83     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243)
#84     Element.rebuild (package:flutter/src/widgets/framework.dart:3947)
#85     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206)
#86     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4381)
#87     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201)
#88     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194)
#89     Element.updateChild (package:flutter/src/widgets/framework.dart:2988)
#90     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243)
#91     Element.rebuild (package:flutter/src/widgets/framework.dart:3947)
#92     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206)
#93     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201)
#94     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194)
#95     Element.updateChild (package:flutter/src/widgets/framework.dart:2988)
#96     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243)
#97     Element.rebuild (package:flutter/src/widgets/framework.dart:3947)
#98     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206)
#99     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201)
#100    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194)
#101    Element.updateChild (package:flutter/src/widgets/framework.dart:2988)
#102    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445)
#103    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194)
#104    Element.updateChild (package:flutter/src/widgets/framework.dart:2988)
#105    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445)
#106    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194)
#107    Element.updateChild (package:flutter/src/widgets/framework.dart:2988)
#108    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243)
#109    Element.rebuild (package:flutter/src/widgets/framework.dart:3947)
#110    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206)
#111    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201)
#112    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194)
#113    Element.updateChild (package:flutter/src/widgets/framework.dart:2988)
#114    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243)
#115    Element.rebuild (package:flutter/src/widgets/framework.dart:3947)
#116    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206)
#117    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201)
#118    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194)
#119    Element.updateChild (package:flutter/src/widgets/framework.dart:2988)
#120    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243)
#121    Element.rebuild (package:flutter/src/widgets/framework.dart:3947)
#122    StatelessElement.update (package:flutter/src/widgets/framework.dart:4298)
#123    Element.updateChild (package:flutter/src/widgets/framework.dart:2977)
#124    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243)
#125    Element.rebuild (package:flutter/src/widgets/framework.dart:3947)
#126    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2432)
#127    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:773)
#128    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:283)
#129    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1102)
#130    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1041)
#131    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:957)
#132    _rootRun (dart:async/zone.dart:1126)
#133    _CustomZone.run (dart:async/zone.dart:1023)
#134    _CustomZone.runGuarded (dart:async/zone.dart:925)
#135    _invoke (dart:ui/hooks.dart:259)
#136    _drawFrame (dart:ui/hooks.dart:217)

**Comment by CarGuo** [comment]
https://github.com/CarGuo/gsy_github_app_flutter/issues/671
