### ISSUE TITLE
请教一个问题，抱歉打扰了

### ISSUE THREAD

**Issue by xuzhenhao** [CarGuo/gsy_github_app_flutter#678]
我开发的一个纯flutter项目，已经替换了mipmap下的5张ic_launcher图片。在部分Android上显示正常，在小米和vivo部分机型上，还是默认的flutter logo。之前怀疑是手机问题,下载了你主页二维码的包，显示又是正常的。请问你是怎么设置的或者有什么思路?

**Comment by CarGuo** [comment]
和 targetSDK 有关，有时候也和这个有关 https://blog.csdn.net/u012881042/article/details/79576824

**Comment by xuzhenhao** [comment]
> 和 targetSDK 有关，有时候也和这个有关 https://blog.csdn.net/u012881042/article/details/79576824

我看看。感谢
