### ISSUE TITLE
请教问题

### ISSUE THREAD

**Issue by albertbxl** [CarGuo/gsy_github_app_flutter#682]
A页面—>PushB页面， 再pop回A页面,  A页面会执行什么方法啊，deactivate方法也不走了吗，flutter 1.17，之前用的flutter 1.12,是会重新调用PageA的deactivate方法

我想要每次回A页面都调接口刷新数据，类似 iOS中， view will appear方法。

 final result = await   Navigator.pushNamed，可以在PageA拿到状态，
但是下面两种不可以：
1. iOS有滑动返回，不走push的回调，
2. A->B->C->D  从D直接返回A,popUntil, 我想要A也刷新数据，
类似于iOS中的view will appear方法，只要页面显示就调用的方法，请问怎么实现？ 万分感谢

**Comment by CarGuo** [comment]
简单点说，可以试试 NavigatorObserver

**Comment by albertbxl** [comment]
好的，非常感谢！
