### ISSUE TITLE
ErrorPage的错误

### ISSUE THREAD

**Issue by ywlyjq** [CarGuo/gsy_github_app_flutter#691]
这下面是错误日志，错误的实现方式，在FlutterReduxApp/WelcomePage的build里使用    
double width = MediaQuery.of(context).size.width;
print(width.toString());
![捕获](https://user-images.githubusercontent.com/18068784/83387076-b0c69580-a41e-11ea-95e0-65896a7bc146.JPG)

**Comment by CarGuo** [comment]
收到～
