### ISSUE TITLE
点击按钮声音反馈是怎么做到的？小白请教

### ISSUE THREAD

**Issue by czeras** [CarGuo/gsy_github_app_flutter#702]

**Comment by CarGuo** [comment]
Flutter 里有 SystemSound 吧？？

**Comment by czeras** [comment]
不知道，好像不不是的，你有找到吗？请指教哦

**Comment by CarGuo** [comment]
SystemSound 的 SystemSoundType 不就是点击 click 么？？

**Comment by czeras** [comment]
你看项目里怎么实现的呢？ 我全局没搜到 SystemSound 和 SystemSoundType 在哪里调用的

**Comment by CarGuo** [comment]
你是哪个 flutter 版本？？我这边有呀 SystemSound

**Comment by czeras** [comment]
Flutter 1.17.2 
代码也是最新的，搜不到 
<img width="665" alt="截屏2020-06-24上午10 02 44" src="https://user-images.githubusercontent.com/35266402/85489058-ffbcb080-b601-11ea-8234-2c3a426e1b85.png">
<img width="654" alt="截屏2020-06-24上午10 02 58" src="https://user-images.githubusercontent.com/35266402/85489074-06e3be80-b602-11ea-82be-0175de457269.png">

**Comment by CarGuo** [comment]
这是项目的包，我这边没有显式调用。
比如 inkWell 的点击，在它内部的 _handleTap 会有 Feedback.forTap(context); ，这个会触发

**Comment by czeras** [comment]
哦，谢谢
