### ISSUE TITLE
可滚动布局有输入框时，弹出键盘后，界面无法自动上移

### ISSUE THREAD

**Issue by zhangwanggit** [CarGuo/gsy_github_app_flutter#704]
我在SingleChildScrollView中有有个输入框，当点击输入框键盘弹起后，界面没有上移，无法滑动，经测试，是项目中如下代码导致，去除后就正常了，不知道为什么

static Widget pageContainer(widget) {
    return MediaQuery(

        ///不受系统字体缩放影响
        data: MediaQueryData.fromWindow(WidgetsBinding.instance.window)
            .copyWith(textScaleFactor: 1),
        child: widget);
  }

**Comment by CarGuo** [comment]
MediaQueryData.fromWindow(WidgetsBinding.instance.window) 换成  MediaQuery.of(context) 试试

**Comment by zhangwanggit** [comment]
> MediaQueryData.fromWindow(WidgetsBinding.instance.window) 换成 MediaQuery.of(context) 试试

换成这个是可以的，初学者，还不懂这个是啥意思，我去研究研究

**Comment by CarGuo** [comment]
这个https://juejin.im/post/5ebe4966e51d454def227b9e ，看下就大概了解了
