### ISSUE TITLE
login_page.dart 中 removeListener 是否有用呢？

### ISSUE THREAD

**Issue by bluescurry** [CarGuo/gsy_github_app_flutter#711]
不太理解 login_page.dart 中在 dispose 生命周期 removeListener 的意义，因为 GSYInputWidget 组件虽然传入了 controller，但是并没有 addListener ，往父组件回传值是使用的 onChange 方法并没有通过 controller，虽然没懂在 dispose 进行 removeListener 的作用，求指教

**Comment by CarGuo** [comment]
因为现在的代码没有用到用户名和密码了，现在用 webview 授权的

**Comment by bluescurry** [comment]
> 因为现在的代码没有用到用户名和密码了，现在用 webview 授权的

您的意思是这块的代码已经被废弃了是吗，我现在在做一些toB的flutter项目，一个表单有16项，因为是需要做自定义校验所以不想用form组件，而是想直接用 TextField 组件，但是每一个 TextField 写一个 Controller 这么就会有很多很多，这让我很苦恼，所以想请教是否有其他更好的方案

**Comment by CarGuo** [comment]
TextField 本身又 onChanged 可以监听，所以你就可以监听到变化，

之后你可以定义一个 CustomForm 用于对应字段在 onChanged 里面去更新，然后 CustomForm 也可以   addListener 和 removeListener

```
class CustomForm extends ChangeNotifier {
  
  String get value1 => _value1;
  
  String _value1;
  set value1(String newValue) {
    if (_value1 == newValue)
      return;
    _value1 = newValue;
    notifyListeners();
  }

  String get value2 => _value2;

  String _value2;
  set value2(String newValue) {
    if (_value2 == newValue)
      return;
    _value2 = newValue;
    notifyListeners();
  }
}


  CustomForm d = CustomForm ();
  d.addListener(() { 
    
  });
```

**Comment by bluescurry** [comment]
> TextField 本身又 onChanged 可以监听，所以你就可以监听到变化，
> 
> 之后你可以定义一个 CustomForm 用于对应字段在 onChanged 里面去更新，然后 CustomForm 也可以 addListener 和 removeListener
> 
> ```
> class CustomForm extends ChangeNotifier {
>   
>   String get value1 => _value1;
>   
>   String _value1;
>   set value1(String newValue) {
>     if (_value1 == newValue)
>       return;
>     _value1 = newValue;
>     notifyListeners();
>   }
> 
>   String get value2 => _value2;
> 
>   String _value2;
>   set value2(String newValue) {
>     if (_value2 == newValue)
>       return;
>     _value2 = newValue;
>     notifyListeners();
>   }
> }
> 
> 
>   CustomForm d = CustomForm ();
>   d.addListener(() { 
>     
>   });
> ```

好的，我研究研究，多谢
