### ISSUE TITLE
对DioError封装方式的疑问

### ISSUE THREAD

**Issue by merlinchen** [CarGuo/gsy_github_app_flutter#732]
我看到您把DioError封装成ResultData是在netFetch中进行的，想请教一下这块的逻辑为什么不放在拦截器的onError里，谢谢！

**Comment by CarGuo** [comment]
嗯嗯，正常应该是在拦截器做的，我这里是只是当时给组员做样例的时候，提供了不同的思路而已。

**Comment by merlinchen** [comment]
多谢指教
