### ISSUE TITLE
国际化获取的时候会不准

### ISSUE THREAD

**Issue by yuxiaoyick** [CarGuo/gsy_github_app_flutter#733]
大佬好，最近在学习大佬项目的时候发现了一个小问题

Locale locale = store.state.platformLocale;

这个代码获取的国际化不会变化；

改成这样就行了 Locale locale = store.state.locale；

嗯，我继续学习了。

**Comment by CarGuo** [comment]
store.state.platformLocale = WidgetsBinding.instance.window.locale;


这个 platformLocale  是获取的平台自己的 locale 
然后如果用户在app设置过 locale ，就用用户设置的，如果没有就用平台的，index 默认是 0

```
  static changeLocale(Store<GSYState> store, int index) {
    Locale locale = store.state.platformLocale;
    if (Config.DEBUG) {
      print(store.state.platformLocale);
    }
    switch (index) {
      case 1:
        locale = Locale('zh', 'CH');
        break;
      case 2:
        locale = Locale('en', 'US');
        break;
    }
    curLocale = locale;
    store.dispatch(RefreshLocaleAction(locale));
  }
```

**Comment by yuxiaoyick** [comment]
但是在切换语言的时候，输出的store.state.platformLocale确实是不变的，会一直是初始化的那个语言，运行的demo是这样的；

**Comment by CarGuo** [comment]
@yuxiaoyick 我测试 demo 切换语言正常呀～

**Comment by yuxiaoyick** [comment]
flutter: en_US
flutter: en_US
flutter: en_US
flutter: en_US
flutter: en_US
flutter: en_US

我切换语言之后就打印这些

会不会是版本的问题？我的是Flutter 1.18.0的版本

**Comment by CarGuo** [comment]
那是因为我在 changeLocale 里面 print 了 platformLocale ，platformLocale 是跟着平台走的，你看下面的方法，用的 locale 是和 index 有关系，index 也就是你选择的语言

**Comment by yuxiaoyick** [comment]
哦～就是说

    Locale locale = store.state.platformLocale;
    locale = Locale('zh', 'CH');

并不会改变 store.state.platformLocale 的值，或者说不会更改 WidgetsBinding.instance.window.locale 的值，是吧？

**Comment by CarGuo** [comment]
WidgetsBinding.instance.window.locale  的值是不会变的，这是平台的当前语言，也就是手机设置里面的语言。
我们改变的语言，是通过改变 GSYLocalizations 里面加载的值来变得

**Comment by yuxiaoyick** [comment]
OK，懂了，感谢解惑
