### ISSUE TITLE
null safety 问题

### ISSUE THREAD

**Issue by ChinaJson** [CarGuo/gsy_github_app_flutter#743]
最新版 null safety 问题如何解决？
![Screen Shot 2020-11-09 at 4 36 38 PM](https://user-images.githubusercontent.com/34496479/98518006-bff11f80-22a9-11eb-96ae-db53556292d7.png)

**Comment by CarGuo** [comment]
1.22.3 是现在的 stable 最新版， 其他非 stable 的暂时不适配哦～
