### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by curryLiu** [CarGuo/gsy_github_app_flutter#744]
升级完cocapods版本1.10.0，
1、运行报错/gsy_github_app_flutter-master/ios/Flutter/Debug.xcconfig:1: could not find included file 'Pods/Target Support Files/Pods-Runner/Pods-Runner.debug.xcconfig' in search paths (in target 'Runner')
2、gsy_github_app_flutter-master/ios/Flutter/Debug.xcconfig:2: could not find included file 'Generated.xcconfig' in search paths (in target 'Runner')
3、gsy_github_app_flutter-master/ios/Flutter/Debug.xcconfig:1: could not find included file 'Pods/Target Support Files/Pods-Runner/Pods-Runner.debug.xcconfig' in search paths (in target 'Runner')

**Comment by CarGuo** [comment]
cocapods 推荐用 1.8-1.9 版本，然后flutter clean 之后再 flutter pub get
