### ISSUE TITLE
项目配置后报错

### ISSUE THREAD

**Issue by PhoenixLeeSin** [CarGuo/gsy_github_app_flutter#748]
郭神， 项目clone后，执行完 flutter packages get后报错。截图如下：
<img width="1273" alt="Snipaste_2020-12-21_09-51-48" src="https://user-images.githubusercontent.com/20637153/102731276-58cb8e00-4372-11eb-82a3-c9f56d63e0d1.png">
<img width="935" alt="Snipaste_2020-12-21_09-52-03" src="https://user-images.githubusercontent.com/20637153/102731284-5c5f1500-4372-11eb-92a0-a56a76a832f3.png">

flutter初学者，求指点

**Comment by CarGuo** [comment]
Flutter SDK 版本是不是 1.22 的版本？

**Comment by PhoenixLeeSin** [comment]
安装的1.22.3的版本

**Comment by CarGuo** [comment]
这个包是 sa_multi_tween 下面的，我这边是 1.1.3，是通过 simple_animations 安装的依赖

**Comment by PhoenixLeeSin** [comment]
重新clone安装依赖还是报同样的错误 用的 mac

**Comment by CarGuo** [comment]
<img width="360" alt="image" src="https://user-images.githubusercontent.com/10770362/102737649-f7f88180-4382-11eb-80b2-4a2ac1c5fba1.png">

<img width="364" alt="image" src="https://user-images.githubusercontent.com/10770362/102737664-034bad00-4383-11eb-9d7b-47a7a62d4fd1.png">


如图，你看看本地的依赖包，  sa_multi_tween 和 simple_animations 是不是如图版本

**Comment by PhoenixLeeSin** [comment]
![image](https://user-images.githubusercontent.com/20637153/102746469-52044180-4399-11eb-90ed-4395e258991a.png)
本地的包里查到了simple_animations版本一致，但是没有找到sa_multi_tween包 好疑惑啊

**Comment by CarGuo** [comment]
我知道了，simple_animations 在升级版本的时候把  sa_multi_tween 删掉了，现在没有 sa_multi_tween，我刚刚更新了代码，你拉一下后重新 flutter pub get 应该就好了

**Comment by PhoenixLeeSin** [comment]
> 我知道了，simple_animations 在升级版本的时候把 sa_multi_tween 删掉了，现在没有 sa_multi_tween，我刚刚更新了代码，你拉一下后重新 flutter pub get 应该就好了

正常了 谢谢郭神
