### ISSUE TITLE
报错了

### ISSUE THREAD

**Issue by dluffymonkey** [CarGuo/gsy_github_app_flutter#750]
![image](https://user-images.githubusercontent.com/8476885/103083348-29897b00-4617-11eb-94a1-25447ef5e782.png)
iPhone12 真机，安全登录成功后运行

![image](https://user-images.githubusercontent.com/8476885/103083462-71a89d80-4617-11eb-8e4c-c045a46d9cd5.png)
iPhone12mini模拟器跑的时候是这样的

**Comment by CarGuo** [comment]
看起来像是网络问题，我这边测试正常。


因为 avatars.githubusercontent.com 和 font 远程服务这些地址是 raw 相关地址，会有时好时不好的情况，不过这个最多就是让图片不显示或者字体显示不正确，不会影响正常使用
