### ISSUE TITLE
电子书籍图片无法加载显示

### ISSUE THREAD

**Issue by Onlylonger** [CarGuo/gsy_github_app_flutter#752]
线上地址：https://guoshuyu.cn/home/wx/Flutter-2.html；

描述：图片不能加载，原因在于 域名为 https 协议，而 资源是 http 协议，浏览器加载报错
![image](https://user-images.githubusercontent.com/19505200/105570766-3cae7880-5d86-11eb-8b76-8a428c426bd5.png)

可以将 cdn 资源地址协议添加 ssl 证书.

**Comment by CarGuo** [comment]
![Screenshot_20210123_214013_com.huawei.browser.jpg](https://user-images.githubusercontent.com/10770362/105579839-ee1fcf00-5dc3-11eb-9abf-32c4fc455513.jpg)



如图所示，我也这边显示正常

**Comment by Onlylonger** [comment]
使用pc浏览器版本如图：

![image](https://user-images.githubusercontent.com/19505200/105625151-1e1daf80-5e62-11eb-9ff7-1f36a4b9176e.png)

目前 微信内置浏览器 和 safari 都可以看到，谷歌浏览器不可以。
