### ISSUE TITLE
用idea模拟器打开登入无法键盘

### ISSUE THREAD

**Issue by mengguagua** [CarGuo/gsy_github_app_flutter#759]
![image](https://user-images.githubusercontent.com/31716403/119095658-1dc6a700-ba45-11eb-8b95-98bb40f4e154.png)
如图，一个上idea运行的，一个上xcode运行的。后者正常，前者不能输入，不能登录，希望前端也可以方便在idea里调试

**Comment by CarGuo** [comment]
如图，iOS 键盘是在模拟器上配置的：

![image](https://user-images.githubusercontent.com/10770362/119101519-a8aaa000-ba4b-11eb-9e5c-124288767faa.png)
