### ISSUE TITLE
flutter是单线程的，如何有效利用现今的多核cpu手机的性能

### ISSUE THREAD

**Issue by hank927** [CarGuo/gsy_github_app_flutter#761]
老师您好，我是最近刚开始学习flutter，看了flutter的原理介绍，是基于单线程的，按我查找的资料来看，一般一个线程都只能在一个cpu的时间切片上运行，像flutter这种机制，能把android的多核cpu都利用起来吗

**Comment by CarGuo** [comment]
首先你可以看这篇 ： https://mp.weixin.qq.com/s/qVAJ6RHfCKBzYhxNUMPXqw

然后 单线程的 只是说每个  dart 都运行在一个独立的 isolate 里面，这个  isolate 默认属于一个线程，但是比如涉及 IO 、网络请求的，都是在 engine 有新的线程做这个，比如移动平台上默认会有四个 Task ，这四个 Task 你可以先简单看作四个线程模式，这部分书里有介绍。

然后渲染是直接通过 GPU 绘制的，利用的是 Skia 的渲染绘制能力，那又是另外的部分了

**Comment by hank927** [comment]
感谢老师

> 首先你可以看这篇 ： https://mp.weixin.qq.com/s/qVAJ6RHfCKBzYhxNUMPXqw
> 
> 然后 单线程的 只是说每个 dart 都运行在一个独立的 isolate 里面，这个 isolate 默认属于一个线程，但是比如涉及 IO 、网络请求的，都是在 engine 有新的线程做这个，比如移动平台上默认会有四个 Task ，这四个 Task 你可以先简单看作四个线程模式，这部分书里有介绍。
> 
> 然后渲染是直接通过 GPU 绘制的，利用的是 Skia 的渲染绘制能力，那又是另外的部分了

感谢老师
