### ISSUE TITLE
登录问题

### ISSUE THREAD

**Issue by finalarcher13** [CarGuo/gsy_github_app_flutter#763]
运行手机是华为mate30pro，在安全登录页面，password的输入键盘智能闪现，没法输入password？因为是网页，不能在Dart代码修改，怎么处理？

**Comment by mimajiushi** [comment]
> 运行手机是华为mate30pro，在安全登录页面，password的输入键盘智能闪现，没法输入password？因为是网页，不能在Dart代码修改，怎么处理？

网页貌似是github的吧，不是作者写的，想改貌似也改不了，有没有可能是flutter插件/flutter官方的bug，建议录个gif瞧瞧

**Comment by finalarcher13** [comment]
@override
  void initState() {
    super.initState();
    if (Platform.isAndroid) WebView.platform = SurfaceAndroidWebView();
  }问题解决，官方建议
