### ISSUE TITLE
.yaml 中的一个小疑问

### ISSUE THREAD

**Issue by muboluo** [CarGuo/gsy_github_app_flutter#765]
Hi，大佬。
我有一个小疑问。

就是在 pubspec.yaml 文件中，我们依赖的第三方库的版本号前的 ^是什么意思？ 加和不加^的区别是什么？
例如：
dependencies:
    google_fonts: ^2.0.0
    google_fonts: 2.0.0

非常感谢

**Comment by CarGuo** [comment]
加了符号表示会使用兼容性现版本升级，比如版本是^2.0.0，但是实际因为库的发布更新了2.0.1，那么实际依赖的可能会是新的 2.0.1而不是2.0.0
当前这个只会发生在小版本更新，大版本不会！
而不加就是固定版本了

**Comment by muboluo** [comment]
感谢大佬解惑
