### ISSUE TITLE
登录页粒子动画问题

### ISSUE THREAD

**Issue by mimajiushi** [CarGuo/gsy_github_app_flutter#766]
打开登陆页，挂应用到后台10s（取10s是因为动画过渡时间最高是`9000milliseconds`），然后再切回来，气泡会全部从底部冒出，没有均匀的效果👇：
![middle_img_v2_dae31324-df08-4e69-97e5-41f549d51fag](https://user-images.githubusercontent.com/33995610/125032868-2771a000-e0c1-11eb-8683-051c4977128b.gif)

原因是应用切后台后动画会停止，等待10s后再切回去，`progress()`返回必定为1，触发了`checkIfParticleNeedsToBeRestarted()`，导致所有粒子的起点时间都相同。

**Comment by CarGuo** [comment]
get～
