### ISSUE TITLE
无法登陆

### ISSUE THREAD

**Issue by Betterforme** [CarGuo/gsy_github_app_flutter#770]
登录404

**Comment by CarGuo** [comment]
如果是下载 apk 的应该没问题，如果是自己编译的，看 readme ，


>### 3、重点：你需要自己在lib/common/config/目录下 创建一个`ignoreConfig.dart`文件，然后输入你申请的Github client_id 和 client_secret。

     class NetConfig {
       static const CLIENT_ID = "xxxx";
     
       static const CLIENT_SECRET = "xxxxxxxxxxx";
     }


   [      注册 Github APP 传送门](https://github.com/settings/applications/new)，当然，前提是你现有一个github账号(～￣▽￣)～ 。
 
### 3、如果使用安全登录（授权登录），那么在上述注册 Github App 的 Authorization callback URL 一栏必须填入 `gsygithubapp://authed`
