### ISSUE TITLE
下载下来 用VSCode 运行报错，信息如下

### ISSUE THREAD

**Issue by Andrew5** [CarGuo/gsy_github_app_flutter#772]
^^^^^^^^^
: Error: Getter not found: 'NetConfig'.
lib/…/dao/user_dao.dart:74
          "client_id": NetConfig.CLIENT_ID,
                       ^^^^^^^^^
: Error: Getter not found: 'NetConfig'.
lib/…/dao/user_dao.dart:75
          "client_secret": NetConfig.CLIENT_SECRET
                           ^^^^^^^^^
    Failed to package /Users/jabraknight/Documents/zkty/customer/my_Flutter/gsy_github_app_flutter.
    Command PhaseScriptExecution failed with a nonzero exit code
    note: Using new build system
    note: Planning
    note: Build preparation complete
    note: Building targets in parallel
    /Users/jabraknight/Documents/zkty/customer/my_Flutter/gsy_github_app_flutter/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.0.99. (in target 'Toast' from project 'Pods')
    /Users/jabraknight/Documents/zkty/customer/my_Flutter/gsy_github_app_flutter/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.0.99. (in target 'Reachability' from project 'Pods')
    /Users/jabraknight/Documents/zkty/customer/my_Flutter/gsy_github_app_flutter/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.0.99. (in target 'FMDB' from project 'Pods')
Could not build the application for the simulator.
Error launching application on iPhone 12.
Exited (sigterm)

**Comment by CarGuo** [comment]
看readme
