### ISSUE TITLE
项目导入一直报错，环境配置无问题，一直提示是v1

### ISSUE THREAD

**Issue by zhangmengjia** [CarGuo/gsy_github_app_flutter#776]
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Warning
──────────────────────────────────────────────────────────────────────────────
Your Flutter application is created using an older version of the Android
embedding. It is being deprecated in favor of Android embedding v2. Follow the
steps at

https://flutter.dev/go/android-project-migration

to migrate your project. You may also pass the --ignore-deprecation flag to
ignore this check and continue with the deprecated v1 embedding. However,
the v1 Android embedding will be removed in future versions of Flutter.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
The detected reason was:

  F:\fproject\gsy_github_app_flutter-master\android\app\src\main\AndroidManifest.xml uses `android:name="io.flutter.app.FutterApplication"`
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Build failed due to use of deprecated Android v1 embedding.

**Comment by CarGuo** [comment]
2.8 的 SDK 版本？？我试了没问题呢

**Comment by zhangmengjia** [comment]
> 2.8 的 SDK 版本？？我试了没问题呢

Flutter 2.9.0-1.0.pre.95  和fluttersdk版本有关系么

**Comment by CarGuo** [comment]
有啊，你这个是 master 的，属于 preview 分支，不是正式版的

 现在正式版本的是 stable 分支的，那才是release版，2.8

**Comment by zhangmengjia** [comment]
FAILURE: Build failed with an exception.

* Where:
Script 'F:\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1070

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'F:\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org


已经换成2.8.0sdk，编译还是有问题，需要配置什么东西么？

**Comment by CarGuo** [comment]
你这个log看不出来什么问题， ` Process 'command 'F:\flutter\bin\flutter.bat'' finished with non-zero exit value 1` 感觉还是你环境有问题

**Comment by zhangmengjia** [comment]
Launching lib\main.dart on TAS AN00 in debug mode...
Running Gradle task 'assembleDebug'...
lib/common/net/address.dart:2:8: Error: Error when reading 'lib/common/config/ignoreConfig.dart': 系统找不到指定的文件�?

import 'package:gsy_github_app_flutter/common/config/ignoreConfig.dart';
       ^
lib/common/dao/user_dao.dart:10:8: Error: Error when reading 'lib/common/config/ignoreConfig.dart': 系统找不到指定的文件�?

import 'package:gsy_github_app_flutter/common/config/ignoreConfig.dart';
       ^
lib/common/net/address.dart:277:13: Error: Undefined name 'NetConfig'.
        "=${NetConfig.CLIENT_ID}&state=app&"
            ^^^^^^^^^
lib/common/dao/user_dao.dart:31:20: Error: Undefined name 'NetConfig'.
      "client_id=${NetConfig.CLIENT_ID}"
                   ^^^^^^^^^
lib/common/dao/user_dao.dart:32:25: Error: Undefined name 'NetConfig'.
      "&client_secret=${NetConfig.CLIENT_SECRET}"
                        ^^^^^^^^^
lib/common/dao/user_dao.dart:74:20: Error: Undefined name 'NetConfig'.
      "client_id": NetConfig.CLIENT_ID,
                   ^^^^^^^^^
lib/common/dao/user_dao.dart:75:24: Error: Undefined name 'NetConfig'.
      "client_secret": NetConfig.CLIENT_SECRET
                       ^^^^^^^^^


我用flutter  doctor 测试环境是没问题，查了一圈子实在是不知道哪里配置又问题

**Comment by CarGuo** [comment]
ignoreConfig.dart 问题看 readme
