### ISSUE TITLE
首页-我的-点搜索图标背景覆盖不全

### ISSUE THREAD

**Issue by Liberations** [CarGuo/gsy_github_app_flutter#782]
左下角会露出一块
![image](https://user-images.githubusercontent.com/16395007/158353489-c02faaca-3c9b-4a54-a423-a8c65e80c6db.png)

**Comment by CarGuo** [comment]
哈哈哈，你看代码，这个是故意的，你不故意还出不了这种效果，这个就是为了给你展示这种实现
