### ISSUE TITLE
Xcode 13.3.1 编译报错

### ISSUE THREAD

**Issue by jiashaoying** [CarGuo/gsy_github_app_flutter#784]
`Flutter 2.10.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 5464c5bac7 (2 days ago) • 2022-04-18 09:55:37 -0700
Engine • revision 57d3bac3dd
Tools • Dart 2.16.2 • DevTools 2.9.2`

Failed to build iOS app
Error output from Xcode build:
↳
    2022-04-20 15:46:15.404 xcodebuild[99989:1299543] Requested but did not find
    extension point with identifier
    Xcode.IDEKit.ExtensionSentinelHostApplications for extension
    Xcode.DebuggerFoundation.AppExtensionHosts.watchOS of plug-in
    com.apple.dt.IDEWatchSupportCore
    2022-04-20 15:46:15.404 xcodebuild[99989:1299543] Requested but did not find
    extension point with identifier
    Xcode.IDEKit.ExtensionPointIdentifierToBundleIdentifier for extension
    Xcode.DebuggerFoundation.AppExtensionToBundleIdentifierMap.watchOS of
    plug-in com.apple.dt.IDEWatchSupportCore
    ** BUILD FAILED **

Xcode's output:
↳
    Writing result bundle at path:
    	/var/folders/pg/nzrj_b6n1xd9dfsgpxzvx1cr0000gn/T/flutter_tools.aawYgy/flutt
    	er_ios_build_temp_diraFCxG5/temporary_xcresult_bundle

    1 warning generated.
    1 warning generated.
    lib/common/net/address.dart:2:8: Error: Error when reading
    'lib/common/config/ignoreConfig.dart': No such file or directory
    import 'package:gsy_github_app_flutter/common/config/ignoreConfig.dart';
           ^
    lib/common/dao/user_dao.dart:10:8: Error: Error when reading
    'lib/common/config/ignoreConfig.dart': No such file or directory
    import 'package:gsy_github_app_flutter/common/config/ignoreConfig.dart';
           ^
    lib/common/net/address.dart:277:13: Error: Undefined name 'NetConfig'.
            "=${NetConfig.CLIENT_ID}&state=app&"
                ^^^^^^^^^
    lib/common/dao/user_dao.dart:31:20: Error: Undefined name 'NetConfig'.
          "client_id=${NetConfig.CLIENT_ID}"
                       ^^^^^^^^^
    lib/common/dao/user_dao.dart:32:25: Error: Undefined name 'NetConfig'.
          "&client_secret=${NetConfig.CLIENT_SECRET}"
                            ^^^^^^^^^
    lib/common/dao/user_dao.dart:74:20: Error: Undefined name 'NetConfig'.
          "client_id": NetConfig.CLIENT_ID,
                       ^^^^^^^^^
    lib/common/dao/user_dao.dart:75:24: Error: Undefined name 'NetConfig'.
          "client_secret": NetConfig.CLIENT_SECRET
                           ^^^^^^^^^
    Failed to package /Users/jiashaoying/github_projects/gsy_github_app_flutter.
    Command PhaseScriptExecution failed with a nonzero exit code
    note: Using new build system
    note: Planning
    note: Build preparation complete
    note: Building targets in dependency order
    /Users/jiashaoying/github_projects/gsy_github_app_flutter/ios/Pods/Pods.xcod
    eproj: warning: The iOS Simulator deployment target
    'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported
    deployment target versions is 9.0 to 15.4.99. (in target 'Toast' from
    project 'Pods')
    /Users/jiashaoying/github_projects/gsy_github_app_flutter/ios/Pods/Pods.xcod
    eproj: warning: The iOS Simulator deployment target
    'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported
    deployment target versions is 9.0 to 15.4.99. (in target 'Reachability' from
    project 'Pods')
    /Users/jiashaoying/github_projects/gsy_github_app_flutter/ios/Pods/Pods.xcod
    eproj: warning: The iOS Simulator deployment target
    'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported
    deployment target versions is 9.0 to 15.4.99. (in target 'FMDB' from project
    'Pods')

    Result bundle written to path:
    	/var/folders/pg/nzrj_b6n1xd9dfsgpxzvx1cr0000gn/T/flutter_tools.aawYgy/flutt
    	er_ios_build_temp_diraFCxG5/temporary_xcresult_bundle

**Comment by CarGuo** [comment]
看 readme

**Comment by jiashaoying** [comment]
自己创建ignoreConfig.dart文件就OK了😓
