### ISSUE TITLE
Flutter Web 运行，在Chrome运行安全登录报错

### ISSUE THREAD

**Issue by jiashaoying** [CarGuo/gsy_github_app_flutter#786]
<img width="336" alt="image" src="https://user-images.githubusercontent.com/8097325/165044266-4743d20b-271a-482e-83de-cd5277fa0a38.png">
 iOS 和 Android运行是正常的，这是什么原因。

**Comment by CarGuo** [comment]
这个项目没支持web，因为github Web 不就是它本体了么…

**Comment by CarGuo** [comment]
项目里不就是用 Github 的 OAuth 授权么？ 只是用的是 WebView ，如果你要用外部浏览器，你就打开外部浏览器，然后在你注册 appid 那里有个 callback ，你填你 app 的隐示调用协议就可以了
