### ISSUE TITLE
编译不起来   环境  win10    flutter 3.0.0   

### ISSUE THREAD

**Issue by JacksonNing** [CarGuo/gsy_github_app_flutter#792]
![1653730907(1)](https://user-images.githubusercontent.com/20626566/170819984-22097072-61ff-467f-b317-bae83264dcb7.jpg)

/D:/SDKSpace/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_redux-0.9.0/lib/flutter_redux.dart:474:22: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
- 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/D:/SDKSpace/flutter/packages/flutter/lib/src/widgets/binding.dart').
package:flutter/…/widgets/binding.dart:1
      WidgetsBinding.instance?.addPostFrameCallback((_) {
                     ^
/D:/SDKSpace/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_redux-0.9.0/lib/flutter_redux.dart:577:22: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
- 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/D:/SDKSpace/flutter/packages/flutter/lib/src/widgets/binding.dart').
package:flutter/…/widgets/binding.dart:1
      WidgetsBinding.instance?.addPostFrameCallback((_) {
                     ^

/D:/SDKSpace/flutter/.pub-cache/hosted/pub.dartlang.org/flare_flutter-3.0.2/lib/flare_render_box.dart:167:26: Warning: Operand of null-aware operation '?.' has type 'SchedulerBinding' which excludes null.
- 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/D:/SDKSpace/flutter/packages/flutter/lib/src/scheduler/binding.dart').
package:flutter/…/scheduler/binding.dart:1
        SchedulerBinding.instance?.cancelFrameCallbackWithId(_frameCallbackID);
                         ^

/D:/SDKSpace/flutter/.pub-cache/hosted/pub.dartlang.org/flare_flutter-3.0.2/lib/flare_render_box.dart:170:28: Warning: Operand of null-aware operation '?.' has type 'SchedulerBinding' which excludes null.
- 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/D:/SDKSpace/flutter/packages/flutter/lib/src/scheduler/binding.dart').
package:flutter/…/scheduler/binding.dart:1
          SchedulerBinding.instance?.scheduleFrameCallback(_beginFrame) ?? -1;
                           ^
/D:/SDKSpace/flutter/.pub-cache/hosted/pub.dartlang.org/flare_flutter-3.0.2/lib/flare_render_box.dart:272:26: Warning: Operand of null-aware operation '?.' has type 'SchedulerBinding' which excludes null.
- 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/D:/SDKSpace/flutter/packages/flutter/lib/src/scheduler/binding.dart').
package:flutter/…/scheduler/binding.dart:1
        SchedulerBinding.instance?.cancelFrameCallbackWithId(_frameCallbackID);
                         ^

/D:/SDKSpace/flutter/.pub-cache/hosted/pub.dartlang.org/win32-2.3.6/lib/src/structs.g.dart:661:31: Error: Member not found: 'UnicodeChar'.
  int get UnicodeChar => Char.UnicodeChar;
                              ^^^^^^^^^^^
/D:/SDKSpace/flutter/.pub-cache/hosted/pub.dartlang.org/win32-2.3.6/lib/src/structs.g.dart:662:38: Error: Setter not found: 'UnicodeChar'.
  set UnicodeChar(int value) => Char.UnicodeChar = value;
                                     ^^^^^^^^^^^

/D:/SDKSpace/flutter/.pub-cache/hosted/pub.dartlang.org/win32-2.3.6/lib/src/structs.g.dart:664:29: Error: Member not found: 'AsciiChar'.
  int get AsciiChar => Char.AsciiChar;
                            ^^^^^^^^^

/D:/SDKSpace/flutter/.pub-cache/hosted/pub.dartlang.org/win32-2.3.6/lib/src/structs.g.dart:665:36: Error: Setter not found: 'AsciiChar'.
  set AsciiChar(int value) => Char.AsciiChar = value;
                                   ^^^^^^^^^

/D:/SDKSpace/flutter/.pub-cache/hosted/pub.dartlang.org/animations-2.0.2/lib/src/open_container.dart:631:24: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.

**Comment by LLLiuWeiJian** [comment]
+++1

**Comment by CarGuo** [comment]
flutter doctor 输出下贴上来看看

我这边提交的 lock 文件里 win32 应该是 win32-2.5.2

**Comment by JacksonNing** [comment]
![1653794520(1)](https://user-images.githubusercontent.com/20626566/170850575-db7f18dd-e994-45db-b490-37ee36f1203e.jpg)

**Comment by CarGuo** [comment]
你更新下代码试试，我测试好像没遇上····
<img width="524" alt="image" src="https://user-images.githubusercontent.com/10770362/170850819-4d64a6ba-760f-456d-9d90-5910aa09c6e2.png">

**Comment by JacksonNing** [comment]
嗯，编译的是android版本    idea用的vscode

**Comment by JacksonNing** [comment]
更新完代码可以了，刚才是什么原因导致的

**Comment by CarGuo** [comment]
应该是官方 path 插件的版本版本有问题…
正常我用的path 应该是 lock 里的 2.5 的 win32，但是你那边get的是2.6.1，所以我做了个升级
