### ISSUE TITLE
Oauth issue

### ISSUE THREAD

**Issue by HikaruIchijyo** [CarGuo/gsy_github_app_flutter#800]
![Screenshot_2022-08-10-09-39-20-746_com.shuyu.gsygithub.gsygithubappflutter.jpg](https://user-images.githubusercontent.com/38470944/183817154-11d43033-5347-4083-8c69-a692e6b826e3.jpg)

**Comment by CarGuo** [comment]
Build project or download apk ？？ All  config like Readme ？

**Comment by HikaruIchijyo** [comment]
> Build project or download apk ？？ All  config like Readme ？

Download apk

**Comment by CarGuo** [comment]
Thx, I found that is some bug with GitHub action config, I update a new apk.  This issue may be solved

**Comment by HikaruIchijyo** [comment]
> Thx, I found that is some bug with GitHub action config, I update a new apk.  This issue may be solved

Sure lemme test
