### ISSUE TITLE
iOS真机和模拟器的底部tabbar安全区背景颜色正常,安卓真机显示底部背景是白色

### ISSUE THREAD

**Issue by XiaBaKe** [CarGuo/gsy_github_app_flutter#804]
<img width="260" alt="image" src="https://user-images.githubusercontent.com/16526785/191400400-7e82cb18-9578-40c2-854d-75eaadade14e.png">
<img width="465" alt="image" src="https://user-images.githubusercontent.com/16526785/191400547-d403b96c-6ebb-45c2-9826-73fe5e29f3d3.png">

**Comment by CarGuo** [comment]
这个是正常预期中的情况

**Comment by XiaBaKe** [comment]
那如果想改变底部颜色需要单独处理吗？

**Comment by CarGuo** [comment]
SystemUiOverlayStyle
