### ISSUE TITLE
无法运行

### ISSUE THREAD

**Issue by ShiChenZhi** [CarGuo/gsy_github_app_flutter#822]
![image](https://user-images.githubusercontent.com/19549491/206139947-8319300c-a2e1-4979-81d5-85175755c746.png)

**Comment by CarGuo** [comment]
测试正常

**Comment by ShiChenZhi** [comment]
请问运行的flutter版本是多少




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CarGuo/gsy_github_app_flutter"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月7日(星期三) 下午5:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [CarGuo/gsy_github_app_flutter] 无法运行 (Issue #822)





 
测试正常

**Comment by CarGuo** [comment]
3.3.9
