### ISSUE TITLE
登录界面的输入框直接长按进入编辑状态之后，键盘弹起会出现一个无法消失的放大镜

### ISSUE THREAD

**Issue by boomery** [CarGuo/gsy_github_app_flutter#835]
flutter中的输入框对于这个放大镜问题有解决方案吗

**Comment by CarGuo** [comment]
配置  TextField

```dart
  magnifierConfiguration: TextMagnifierConfiguration(magnifierBuilder: (
          BuildContext context,
          MagnifierController controller,
          ValueNotifier<MagnifierInfo> magnifierInfo,
        ) {
          return null;
        })
```

试试？

**Comment by boomery** [comment]
感谢大佬，这个能解决问题。还有个疑问，输入框的长按功能键是在哪里配置的呢，我翻了代码没看出来，是用了插件还是什么，刚开始学，没看明白 😅

**Comment by CarGuo** [comment]
有个  contextMenuBuilder 参数

**Comment by hanshengjian** [comment]
> 配置 TextField
> 
> ```dart
>   magnifierConfiguration: TextMagnifierConfiguration(magnifierBuilder: (
>           BuildContext context,
>           MagnifierController controller,
>           ValueNotifier<MagnifierInfo> magnifierInfo,
>         ) {
>           return null;
>         })
> ```
> 
> 试试？

flutter 3.3.10 编译报错

**Comment by CarGuo** [comment]
https://github.com/CarGuo/gsy_github_app_flutter#5运行之前请注意下 @hanshengjian
