### ISSUE TITLE
配置了的，我能正常登陆GitHub网页端，但是跑起来，就报422

### ISSUE THREAD

**Issue by woaini521** [CarGuo/gsy_github_app_flutter#849]
配置了的，我能正常登陆GitHub网页端，但是跑起来，就报422

_Originally posted by @chenxihub in https://github.com/CarGuo/gsy_github_app_flutter/issues/13#issuecomment-419604732_

**Comment by woaini521** [comment]
问下Homepage URL 应该填写？

**Comment by CarGuo** [comment]
gsygithubapp://authed

**Comment by woaini521** [comment]
Authorization callback URL  和 Homepage URL 都填写  gsygithubapp://authed   ？

**Comment by woaini521** [comment]
问下flutter如何获取跳转页面的url?
