### ISSUE TITLE
编译失败

### ISSUE THREAD

**Issue by tianshaokai** [CarGuo/gsy_github_app_flutter#860]
One or more issues found when checking AAR metadata values:
     
     The minCompileSdk (31) specified in a
     dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
     is greater than this module's compileSdkVersion (android-29).
     Dependency: androidx.window:window-java:1.0.0-beta04.
     AAR metadata file: /Users/xiaobao/.gradle/caches/transforms-3/5cdc6ff012c2642ae0b17cac4608bd36/transformed/jetified-window-java-1.0.0-beta04/META-INF/com/android/build/gradle/aar-metadata.properties.
     
     The minCompileSdk (31) specified in a
     dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
     is greater than this module's compileSdkVersion (android-29).
     Dependency: androidx.window:window:1.0.0-beta04.
     AAR metadata file: /Users/xiaobao/.gradle/caches/transforms-3/e3fb8849fda8212e93ddc75a93e65816/transformed/jetified-window-1.0.0-beta04/META-INF/com/android/build/gradle/aar-metadata.properties.
     
     The minCompileSdk (32) specified in a
     dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
     is greater than this module's compileSdkVersion (android-29).
     Dependency: androidx.webkit:webkit:1.5.0.
     AAR metadata file: /Users/xiaobao/.gradle/caches/transforms-3/e6ad915c58ea43049220ff4368b6515a/transformed/webkit-1.5.0/META-INF/com/android/build/gradle/aar-metadata.properties.
     
     The minCompileSdk (33) specified in a
     dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
     is greater than this module's compileSdkVersion (android-29).
     Dependency: androidx.core:core:1.10.1.
     AAR metadata file: /Users/xiaobao/.gradle/caches/transforms-3/e6c7144b059ce69ee04d1632ecbb731a/transformed/core-1.10.1/META-INF/com/android/build/gradle/aar-metadata.properties.
     
     The minCompileSdk (33) specified in a
     dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
     is greater than this module's compileSdkVersion (android-29).
     Dependency: androidx.annotation:annotation-experimental:1.3.0.
     AAR metadata file: /Users/xiaobao/.gradle/caches/transforms-3/b0f7cc7fb17f410187f6f2d5921c535b/transformed/jetified-annotation-experimental-1.3.0/META-INF/com/android/build/gradle/aar-metadata.properties.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.3/userguide/command_line_interface.html#sec:command_line_warnings

**Comment by CarGuo** [comment]
麻烦提供一下你的 pubspec.lock 的内容我对比下

**Comment by CarGuo** [comment]
可以更新下最新代码尝试，刚好升级了一批依赖
