### ISSUE TITLE
想问一下作者flutter sdk 版本如何随着项目切换版本

### ISSUE THREAD

**Issue by tianshaokai** [CarGuo/gsy_github_app_flutter#861]
我发现网上下载一个开源项目，它用的flutter 版本和自己用的版本不一样， 本地下载了多个flutter 版本，发现吧没办法随意切换，并且发现，flutter pub get 缓存还有一些冲突，问问作者是如何解决这些问题的

**Comment by CarGuo** [comment]
https://pub-web.flutter-io.cn/packages/fvm
