### ISSUE TITLE
 Could not resolve net.sf.proguard:proguard-base:6.0.3.

### ISSUE THREAD

**Issue by ttylinux** [CarGuo/gsy_github_app_flutter#885]
编译失败，这个异常无法修复？

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':flutter_inappwebview'.
> Could not resolve all files for configuration ':flutter_inappwebview:classpath'.
   > Could not resolve net.sf.proguard:proguard-base:6.0.3.
     Required by:
         project :flutter_inappwebview > com.android.tools.build:gradle:4.1.0 > net.sf.proguard:proguard-gradle:6.0.3
      > Could not resolve net.sf.proguard:proguard-base:6.0.3.
         > Could not parse POM https://repo.maven.apache.org/maven2/net/sf/proguard/proguard-base/6.0.3/proguard-base-6.0.3.pom
            > ǰ���в����������ݡ�
> Failed to notify project evaluation listener.
   > Could not get unknown property 'android' for project ':flutter_inappwebview' of type org.gradle.api.Project.
   > Could not get unknown property 'android' for project ':flutter_inappwebview' of type org.gradle.api.Project.

**Comment by ttylinux** [comment]
怎么修复这个异常？

**Comment by CarGuo** [comment]
Could not resolve net.sf.proguard:proguard-base:6.0.3. ， Could not parse POM ，网络问题
