### ISSUE TITLE
Public feedback

### ISSUE THREAD

**Issue by ccoVeille** [CarGuo/gsy_github_app_flutter#887]
Yesterday I wrote a feedback in the app. I sent like a message in a bottle.

Today, I discovered you fixed it

- #886

Thanks for this.

But I have to share my surprise to see that my feedback was public and made by my own account.

I do find it's a very good idea to proceed like this, BUT you should warn the user about it in a confirmation message.

People may share personal or sensitive information and everyone could have access to it.

Please note, I may have misunderstood the processe, but I wanted to share my feeling about what I understood

**Comment by CarGuo** [comment]
yes, your are right ~ fix & release 6.1.0

**Comment by ccoVeille** [comment]
Thanks
