### ISSUE TITLE
Question on permissions

### ISSUE THREAD

**Issue by IzzySoft** [CarGuo/gsy_github_app_flutter#890]
I've received warnings from a scanner here at IoD:

```
! repo/com.shuyu.gsygithub.gsygithubappflutter_55.apk declares sensitive permission(s): android.permission.READ_EXTERNAL_STORAGE*
! repo/com.shuyu.gsygithub.gsygithubappflutter_55.apk contains signature block blobs: 0x504b4453 (DEPENDENCY_INFO_BLOCK; GOOGLE)
```

`READ_EXTERNAL_STORAGE` was granted implicitly (as the asterisk indicated) as the app requests the write permission. Could you please clarify what that is needed for?

As for `DEPENDENCY_INFO_BLOCK`, that can easily be avoided with a tiny adjustment in your `build.gradle`:

```gradle
android {
    dependenciesInfo {
        // Disables dependency metadata when building APKs.
        includeInApk = false
        // Disables dependency metadata when building Android App Bundles.
        includeInBundle = false
    }
}
```

For some background: that BLOB is supposed to be just a binary representation of your app's dependency tree. But as it's encrypted with a public key belonging to Google, only Google can read it – and nobody else can even verify what it really contains. More details can be found e.g. here: [Ramping up security: additional APK checks are in place with the IzzyOnDroid repo](https://android.izzysoft.de/articles/named/iod-scan-apkchecks#blobs).

Thanks in advance!

**Comment by CarGuo** [comment]
Because before this, the program had `saveImage` related logic, but it is currently blocked in the relevant code.
For now, it can be removed

**Comment by IzzySoft** [comment]
Thanks!

**Comment by TotallyAvailable** [comment]
@CarGuo ***Please*** remember to set the GITHUB_TOKEN permissions (alongside 'persist-credentials', 'Secret Source') for **all** workflows (and across all projects) to the ***absolute minimum*** necessary to avoid further use of **default read+write-all** tokens.

This message has **nothing** to do with this PR/Issue and should only be seen as a heads-up to reduce the risk of leaking highly privileged tokens in the future. This issue affects far more projects than anyone seems to care about, including GitHub itself. ~~Should this scenario not be of concern, ignore this message.~~ This information is ***not new, secret or confidential.*** Old Issue/PR used for "reduced visibility purposes". Apologies again for using this way of reaching out.

Also ***if*** the workflow relies on ```build.gradle``` for signing *releases*.... that might be a problem ?

<details>

```
    signingConfigs {
        debug {
            storeFile file("../gsygithubapp-debug.jks")
            storePassword "123456"
            keyAlias "debug"
            keyPassword "123456"
        }
        release {
            storeFile file("../gsygithubapp-debug.jks")
            storePassword "123456"
            keyAlias "debug"
            keyPassword "123456"
        }
    }

    buildTypes {
        debug {
            signingConfig signingConfigs.debug
        }
        release {
            signingConfig signingConfigs.release
        }
    }
```

</details>
