### ISSUE TITLE
GSYGithubAppFlutter on OpenAPK

### ISSUE THREAD

**Issue by mobilenetworkltd** [CarGuo/gsy_github_app_flutter#891]
Hey,

I'm running a open source repo for Android apps at https://www.openapk.net and I would like to have GSYGithubAppFlutter listed in the repo. Please review the listing at https://www.openapk.net/gsygithubappflutter/com.shuyu.gsygithub.gsygithubappflutter/

It is hooked to your GitHub repo so all the updates are automatically pushed to OpenAPK. Let me know if its ok !

If you are interested you can link to it and use our download banners ( https://www.openapk.net/images/openapk-badge.png )

**Comment by CarGuo** [comment]
ok～

**Comment by mobilenetworkltd** [comment]
Thank you for putting our banner on GSYGithubAppFlutter's page. Just to note that it is linking to https://camo.githubusercontent.com/28f30947df6355496a95b7c6d9930a15576d50aecc2ee68e865a0332bfb1d6cc/68747470733a2f2f7777772e6f70656e61706b2e6e65742f696d616765732f6f70656e61706b2d62616467652e706e67 if you missed the link to OpenAPK.

 I would be glad if you have some feedback about our site and will greatly appreciate some suggestions.
